=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/NotUsed/package.dtd
<!-- Root fileElement -->
<!ELEMENT root (projectActionList|xi:include)* >
   <!ATTLIST root version  CDATA #REQUIRED >
   <!ATTLIST root xmlns:xi CDATA #IMPLIED >

<!ELEMENT xi:include EMPTY >
   <!ATTLIST xi:include href CDATA #REQUIRED >

 <!ELEMENT page (group)* >
   <!ATTLIST page id          CDATA #REQUIRED>
   <!ATTLIST page name        CDATA #REQUIRED>
   <!ATTLIST page description CDATA #REQUIRED>

 <!ELEMENT group EMPTY >
   <!ATTLIST group id    CDATA #REQUIRED>
   <!ATTLIST group name  CDATA #REQUIRED>
   <!ATTLIST group row   CDATA #IMPLIED>
   <!ATTLIST group col   CDATA #IMPLIED>
   <!ATTLIST group width CDATA "1">
   <!ATTLIST group span  CDATA "1">
 
<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList (applyWhen?, (page|projectActionList|variable|constant|excludeSourceFile|excludeSourceFolder|createFolder|deleteResource|copy|projectOption|customAction|xi:include)*)>
   <!ATTLIST projectActionList id    ID     #IMPLIED>
   <!ATTLIST projectActionList root  CDATA  #IMPLIED>

<!-- Condition controlling when list action is applied -->
<!ELEMENT applyWhen (and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches|hardwareIs|hardwareMatches|requirement|preclusion)>

<!ELEMENT and ((and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches|hardwareIs|hardwareMatches|requirement|preclusion)*) >
<!ELEMENT or  ((and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches|hardwareIs|hardwareMatches|requirement|preclusion)*) >
<!ELEMENT not  (and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches|hardwareIs|hardwareMatches|requirement|preclusion) >

<!-- Condition controlling when list action is applied -->
<!ELEMENT enableWhen (and|or|not|requirement|preclusion)>

<!-- Allows dynamic checking if a dialogue check-box is selected -->
<!ELEMENT requirement EMPTY >
   <!ATTLIST requirement idRef CDATA #REQUIRED>

<!-- Allows dynamic checking if a dialogue check-box is not selected -->
<!ELEMENT preclusion EMPTY >
   <!ATTLIST preclusion idRef CDATA #REQUIRED>

<!-- Allows testing of a variable -->
<!ELEMENT variableRef EMPTY >
   <!ATTLIST variableRef condition 		(isTrue|isDefined|matches|lessThan|lessThanOrEqual|equal|greaterThan|greaterThanOrEqual) "isTrue">
   <!ATTLIST variableRef idRef         CDATA    #REQUIRED>
   <!ATTLIST variableRef value         CDATA    #IMPLIED>
   <!ATTLIST variableRef defaultValue  CDATA    #IMPLIED>

<!ELEMENT deviceNameIs (#PCDATA) >
<!ELEMENT deviceFamilyIs (#PCDATA) >
<!ELEMENT deviceSubfamilyIs (#PCDATA) >
<!ELEMENT deviceNameMatches (#PCDATA) >
<!ELEMENT deviceFamilyMatches (#PCDATA) >
<!ELEMENT deviceSubfamilyMatches (#PCDATA) >
<!ELEMENT hardwareIs (#PCDATA) >
<!ELEMENT hardwareMatches (#PCDATA) >

<!ELEMENT projectActionListRef EMPTY>
   <!ATTLIST projectActionListRef ref IDREF #REQUIRED>
 
<!-- Variable controlling a block -->
<!ELEMENT variable (enableWhen*) >
   <!ATTLIST variable id           CDATA #REQUIRED>
   <!ATTLIST variable name         CDATA #IMPLIED>
   <!ATTLIST variable description  CDATA #IMPLIED>
   <!ATTLIST variable type         (boolean|int|string) 	"boolean" >
   <!ATTLIST variable defaultValue CDATA #IMPLIED>
   <!ATTLIST variable values       CDATA #IMPLIED>
   <!ATTLIST variable checkGroup   CDATA #IMPLIED>
   <!ATTLIST variable radioGroup   CDATA #IMPLIED>
   
<!ELEMENT constant EMPTY >
   <!ATTLIST constant id           CDATA #REQUIRED>
   <!ATTLIST constant value        CDATA #REQUIRED>
   <!ATTLIST constant type         (boolean|int|string)  "string" >
   <!ATTLIST constant weak         (true|false)          "false">
   <!ATTLIST constant overwrite    (true|false)          "false">
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    (source|include|normal) "normal">

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source                CDATA #REQUIRED>
   <!ATTLIST copy target                CDATA #REQUIRED>
   <!ATTLIST copy type                  CDATA #IMPLIED>
   <!ATTLIST copy sourcePathType        (absolute|relative|unknown) #IMPLIED>
   <!ATTLIST copy macroReplace          (true|false) "true">
   <!ATTLIST copy overwrite             (true|false) "false">
   <!ATTLIST copy derived               (true|false) "false">
   
<!-- Eclipse project options (for gcc, gdb etc) -->
<!ELEMENT projectOption (value*)>
   <!ATTLIST projectOption id        CDATA                #REQUIRED>
   <!ATTLIST projectOption config    (all|release|debug)  "all">
   <!ATTLIST projectOption overwrite (true|false)         "false">

<!-- Custom build action -->
<!ELEMENT customAction (value)* >
   <!ATTLIST customAction class       CDATA #REQUIRED>
   
<!-- Attribute value for projectOption --> 
<!ELEMENT value (#PCDATA)>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/30.Options-file-list-MKLxxZ4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Extra Optional files for MK1x MKL2x MKL3x -->
   <projectActionList id="Options-file-list-MKLxxZ4">
      <applyWhen>
         <and>
            <or>
               <deviceSubfamilyIs>MKL14Z4</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKL15Z4</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKL16Z4</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKL24Z4</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKL25Z4</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKL26Z4</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKL34Z4</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKL36Z4</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKL46Z4</deviceSubfamilyIs>
            </or>
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>
      <!-- Clock -->
      <copy source="Startup_Code/clock-MCG-MKLxx.c"              target="Startup_Code/clock.c"              overwrite="always" />
      <copy source="Project_Headers/clock_configure-MCG-MKLxx.h" target="Project_Headers/clock_configure.h" overwrite="always" />
      <!-- Console -->
      <copy source="Startup_Code/console-mkl.c"    target="Startup_Code/console.c"    overwrite="always" />
      <copy source="Project_Headers/console.h"     target="Project_Headers/console.h" overwrite="always" />
   </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/NotUsed/40.CPP-abstraction-TPM.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "package.dtd">

<root version="1.0" >
   <projectActionList id="CPP-abstraction-ADC" >
      <applyWhen>
         <and>
            <variableRef idRef="cpp.peripheral.internal.tpm" />
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>

      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.CPP-abstraction" condition="isTrue"/>
         </applyWhen>
   
         <!-- MK ADC CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen>
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MK.*</deviceSubfamilyMatches>
                     </or>
                  </and>
               </applyWhen>
               <copy source="Project_Headers/tpm.h"                              target="Project_Headers/tpm.h" />
               <copy source="Snippets/tpm-pwm-example.cpp"                           target="Snippets/tpm-pwm-example.cpp" />
            </projectActionList>
         </projectActionList>
         
         <!-- MKL ADC CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen>
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MKL.*</deviceSubfamilyMatches>
                        <deviceSubfamilyMatches>MKE.*</deviceSubfamilyMatches>
                     </or>
                  </and>
               </applyWhen>
               <copy source="Project_Headers/tpm.h"                              target="Project_Headers/tpm.h" />
               <copy source="Snippets/tpm-pwm-example.cpp"                           target="Snippets/tpm-pwm-example.cpp" />
            </projectActionList>
         </projectActionList>
         
         <!-- MKM ADC CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen >
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MKM.*</deviceSubfamilyMatches>
                     </or>
                  </and>
               </applyWhen>
            </projectActionList>
         </projectActionList>
      </projectActionList>
   </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/20.CPP-abstraction-MK22FA12.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd"
[
<!ENTITY DEVICE_SUB_FAMILY  "MK22FA12">
<!ENTITY DEVICE_FAMILY      "MK">
<!ENTITY DEVICE_FILE        "MK22FA12">
]>

<root version="1.0" >
   <projectActionList id="CPP-abstraction-&DEVICE_SUB_FAMILY;">
      <applyWhen>
         <and>
            <deviceSubfamilyIs>&DEVICE_SUB_FAMILY;</deviceSubfamilyIs>
            <variableRef idRef="hasCCNature" condition="isTrue" />
         </and>
      </applyWhen>

      <!-- Affects later CPP peripheral options -->
      <constant id="cpp.peripheral.subfamily"       value="&DEVICE_SUB_FAMILY;" />
      
      <!-- These constants enable peripheral features -->
      <constant id="cpp.peripheral.internal.adc"    value="true" />
      <constant id="cpp.peripheral.internal.ftm"    value="true" />
      <constant id="cpp.peripheral.internal.i2c"    value="true" />
      <constant id="cpp.peripheral.internal.lptmr"  value="true" />
      <constant id="cpp.peripheral.internal.pit"    value="true" />
      <constant id="cpp.peripheral.internal.spi"    value="true" />

      <variable id="projectOptionValue.CPP-abstraction" 
         name="CPP Hardware abstraction" 
         description="Adds a CPP abstraction layer for hardware\n(GPIO, ADC, PWM) - &DEVICE_SUB_FAMILY;"
         checkGroup="group-additional-options" />
      <projectActionList>
         <applyWhen >
            <variableRef idRef="projectOptionValue.CPP-abstraction" />
         </applyWhen>

      </projectActionList>
   </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/NotUsed/46.CPP-abstraction-SPI.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "package.dtd">

<root version="1.0" >
   <projectActionList id="CPP-abstraction-SPI" >
      <applyWhen>
         <and>
            <or>
               <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
            </or>
            <variableRef idRef="cpp.peripheral.internal.spi" />
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>

      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.CPP-abstraction" condition="isTrue"/>
         </applyWhen>
         <variable id="projectOptionValue.CPP-abstraction-SPI" 
            name="SPI interface" 
            description="Adds a CPP abstraction layer for SPI hardware" 
            checkGroup="group-peripheral-options" >
         </variable>
   
         <!-- MK SPI CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen>
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
                     </or>
                     <variableRef idRef="projectOptionValue.CPP-abstraction-SPI" />
                  </and>
               </applyWhen>
               <copy source="Project_Headers/spi-MK.h"        target="Project_Headers/spi.h" />
               <copy source="Sources/spi-MK.cpp"              target="Sources/spi.cpp" />
            </projectActionList>
         </projectActionList>
         
         <!-- MKL SPI CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen>
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
                     </or>
                     <variableRef idRef="projectOptionValue.CPP-abstraction-SPI" />
                  </and>
               </applyWhen>
               <copy source="Project_Headers/spi-MKL.h"        target="Project_Headers/spi.h" />
               <copy source="Project_Headers/dma-MKL.h"        target="Project_Headers/dma.h" />
               <copy source="Sources/spi-MKL.cpp"              target="Sources/spi.cpp" />
               <copy source="Sources/dma-MKL.cpp"              target="Sources/dma.cpp" />
            </projectActionList>
         </projectActionList>
      </projectActionList>
   </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/400.Kinetis_SDK/60_00.KSDK_usb_host_msd_fatfs.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd"
[
<!ENTITY usb-include-paths  SYSTEM "includes/00_00.usb_includes.xml">
]>

<root version="1.0" >
   <!-- Freescale group-ksdk-demos -->
   <projectActionList id="demo.KSDK-usb-host-msd-fatfs" root="">
      <applyWhen>
         <and>
            <variableRef idRef="demo.KSDK-usb-host-msd-fatfs" />
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>
      <projectActionList>
         <applyWhen>
            <and>
               <variableRef idRef="projectOptionValue.Kinetis-SDK-enable" />
               <or>
                  <variableRef idRef="projectOptionValue.Kinetis-SDK-os-bare-metal" />
                  <and>
                     <variableRef idRef="demo.KSDK-usb-with-rtos"/>
                     <or>
                        <variableRef idRef="projectOptionValue.Kinetis-SDK-os-free-rtos" />
                        <variableRef idRef="projectOptionValue.Kinetis-SDK-os-mqx" />
                        <variableRef idRef="projectOptionValue.Kinetis-SDK-os-ucosii" />
                        <variableRef idRef="projectOptionValue.Kinetis-SDK-os-ucosiii" />
                     </or>
                  </and>
               </or>
            </and>
         </applyWhen>
         <variable id="projectOptionValue.KSDK-usb-host-msd-fatfs" 
            name="USB Host MSD FATFS example" 
            description="The board will transfer data from an attached USB FAT formatted disk"
            radioGroup="group-ksdk-demo" >
         </variable>
         <projectActionList>
            <applyWhen>
               <variableRef idRef="projectOptionValue.KSDK-usb-host-msd-fatfs" />
            </applyWhen>
            <deleteResource target="Sources/main.c" />
         
            <copy source="usbdm_kds_path/examples/$(demo.KDS.boardName)/demo_apps/usb/host/msd/msd_fatfs/readme.pdf" type="link" target="doc/readme.pdf"      sourcePathType="absolute" />
   
            <copy source="usbdm_kds_path/examples/$(demo.KDS.boardName)/demo_apps/usb/host/msd/msd_fatfs/hardware_init.c"    target="board/hardware_init.c"   sourcePathType="absolute" />
            
            <copy source="usbdm_kds_path/middleware/filesystem/fatfs/fsl_usb_disk/src/msd_diskio.c"          target="Sources/msd_diskio.c"                 sourcePathType="absolute" />
            <copy source="usbdm_kds_path/middleware/filesystem/fatfs/fsl_usb_disk/msd_diskio.h"              target="Sources/msd_diskio.h"                 sourcePathType="absolute" />
   
            <copy source="usbdm_kds_path/middleware/filesystem/fatfs/diskio.c"            target="Sources/fatfs/diskio.c"  sourcePathType="absolute" />
            <copy source="usbdm_kds_path/middleware/filesystem/fatfs/diskio.h"            target="Sources/fatfs/diskio.h"  sourcePathType="absolute" />
            <copy source="usbdm_kds_path/middleware/filesystem/fatfs/ff.c"                target="Sources/fatfs/ff.c"      sourcePathType="absolute" />
            <copy source="usbdm_kds_path/middleware/filesystem/fatfs/ff.h"                target="Sources/fatfs/ff.h"      sourcePathType="absolute" />
            <copy source="usbdm_kds_path/middleware/filesystem/fatfs/ffconf.h"            target="Sources/fatfs/ffconf.h"  sourcePathType="absolute" />
            <copy source="usbdm_kds_path/middleware/filesystem/fatfs/option/unicode.c"    target="Sources/fatfs/option/unicode.c" sourcePathType="absolute" />
   
            <copy source="usbdm_kds_path/examples/$(demo.KDS.boardName)/demo_apps/usb/host/msd/msd_fatfs/main.c"          target="Sources/main.c"                 sourcePathType="absolute" />
            <copy source="usbdm_kds_path/examples/$(demo.KDS.boardName)/demo_apps/usb/host/msd/msd_fatfs/msd_fat_demo.c"  target="Sources/msd_fat_demo.c"         sourcePathType="absolute" />

            <!-- C Include paths -->
            <projectOption id="net.sourceforge.usbdm.gnu.c.compiler.option.include.paths">
               &usb-include-paths;
               <value>&quot;${workspace_loc:/${ProjName}/Sources/fatfs}&quot;</value>
            </projectOption>
            
            <!-- C++ Include paths -->
            <projectOption id="net.sourceforge.usbdm.gnu.cpp.compiler.option.include.paths">
               &usb-include-paths;
               <value>&quot;${workspace_loc:/${ProjName}/Sources/fatfs}&quot;</value>
            </projectOption>
         <!-- C Defines -->
         <projectOption id="net.sourceforge.usbdm.gnu.c.compiler.option.preprocessor.def.symbols">
            <value>USB_DISK_ENABLE=1</value>
         </projectOption>
         <!-- C++ Defines -->
         <projectOption id="net.sourceforge.usbdm.gnu.cpp.compiler.option.preprocessor.def.symbols">
            <value>USB_DISK_ENABLE=1</value>
         </projectOption>
            <!-- C Link options -->
            <projectOption id="gnu.c.link.option.other" overwrite="always">
               <value>&quot;--defsym=__ram_vector_table__=1&quot;</value>
            </projectOption>
            <!-- C++ Link options -->
            <projectOption id="gnu.cpp.link.option.other" overwrite="always">
               <value>&quot;--defsym=__ram_vector_table__=1&quot;</value>
            </projectOption>
         </projectActionList>
      </projectActionList>
   </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/Options-file-list-MKMxxZ5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Extra Optional files for MKMxx -->
   <projectActionList id="Options-file-list-MKMxxZ5">
      <applyWhen>
         <and>
            <or>
               <deviceSubfamilyIs>MKM14Z5</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKM33Z5</deviceSubfamilyIs>
               <deviceSubfamilyIs>MKM34Z5</deviceSubfamilyIs>
            </or>
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>
      <variable id="projectOptionValue.Clock-setup" 
         name="Clock setup code" 
         description="Adds code for basic clock initialization - check assumptions made"
         checkGroup="group-additional-options"/>
      <variable id="projectOptionValue.UART-setup" 
         name="UART setup code" 
         description="Adds C stdio (UART) support for newlib"          
         checkGroup="group-additional-options" >
         <enableWhen>
            <requirement idRef="projectOptionValue.Clock-setup"/>
         </enableWhen>
      </variable>
      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.Clock-setup" />
         </applyWhen>
         <copy source="Startup_Code/clock-MKMxx.c" target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-MKMxx.h" target="Project_Headers/clock_configure.h" />
      </projectActionList>
      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.UART-setup" />
         </applyWhen>
         <copy source="Startup_Code/uart-mkm.c" target="Startup_Code/uart.c" />
         <copy source="Project_Headers/uart.h" target="Project_Headers/uart.h" />
      </projectActionList>
   </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/50.CPP-abstraction-OLED_SSD1306.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >
   <projectActionList id="CPP-abstraction-SSD1306_OLED" >
      <applyWhen>
         <and>
            <or>
               <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
            </or>
            <variableRef idRef="cpp.peripheral.internal.i2c" />
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>
      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.CPP-abstraction" condition="isTrue"/>
         </applyWhen>
         <variable id="projectOptionValue.CPP-abstraction-SSD1306_OLED" 
            name="SSD1306_OLED C++ interface" 
            description="Adds a CPP abstraction layer for a SSD1306 based OLED" 
            checkGroup="group-i2c-peripheral-options" >
         </variable>
   
         <!-- I2C CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen >
                  <variableRef idRef="projectOptionValue.CPP-abstraction-SSD1306_OLED" />
               </applyWhen>
               <copy source="Snippets/oled-example.cpp"     target="Snippets/oled-example.cpp"  overwrite="true" />
               <copy source="Snippets/fonts.h"              target="Sources/fonts.h"            overwrite="true" />
               <copy source="Snippets/fonts.cpp"            target="Sources/fonts.cpp"          overwrite="true" />
               <copy source="Snippets/oled.h"               target="Sources/oled.h"             overwrite="true" />
               <copy source="Snippets/oled.cpp"             target="Sources/oled.cpp"           overwrite="true" />
            </projectActionList>
         </projectActionList>
      </projectActionList>
    </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/NotUsed/50.CPP-abstraction-HMC5883L.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "package.dtd">

<root version="1.0" >
   <projectActionList id="CPP-abstraction-HMC5883L" >
      <applyWhen>
         <and>
            <or>
               <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
            </or>
            <variableRef idRef="cpp.peripheral.internal.i2c" />
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>
      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.CPP-abstraction" condition="isTrue"/>
         </applyWhen>
         <variable id="projectOptionValue.CPP-abstraction-HMC5883L" 
            name="HMC5883L C++ interface" 
            description="Adds a CPP abstraction layer for HMC5883L accelerometer" 
            checkGroup="group-i2c-peripheral-options" >
         </variable>
   
         <!-- I2C CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen >
                  <variableRef idRef="projectOptionValue.CPP-abstraction-HMC5883L" />
               </applyWhen>
               <copy source="Snippets/hmc5883l-example.cpp"     target="Snippets/hmc5883l-example.cpp" />
               <copy source="Project_Headers/hmc5883l.h"        target="Project_Headers/hmc5883l.h" />
               <copy source="Sources/hmc5883l.cpp"              target="Sources/hmc5883l.cpp" />
            </projectActionList>
         </projectActionList>
      </projectActionList>
    </projectActionList>
</root>
