=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/NotUsed/package.dtd
<!-- Root fileElement -->
<!ELEMENT root (projectActionList|xi:include)* >
   <!ATTLIST root version  CDATA #REQUIRED >
   <!ATTLIST root xmlns:xi CDATA #IMPLIED >

<!ELEMENT xi:include EMPTY >
   <!ATTLIST xi:include href CDATA #REQUIRED >

 <!ELEMENT page (group)* >
   <!ATTLIST page id          CDATA #REQUIRED>
   <!ATTLIST page name        CDATA #REQUIRED>
   <!ATTLIST page description CDATA #REQUIRED>

 <!ELEMENT group EMPTY >
   <!ATTLIST group id    CDATA #REQUIRED>
   <!ATTLIST group name  CDATA #REQUIRED>
   <!ATTLIST group row   CDATA #IMPLIED>
   <!ATTLIST group col   CDATA #IMPLIED>
   <!ATTLIST group width CDATA "1">
   <!ATTLIST group span  CDATA "1">
 
<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList (applyWhen?, (page|projectActionList|variable|constant|excludeSourceFile|excludeSourceFolder|createFolder|deleteResource|copy|projectOption|customAction|xi:include)*)>
   <!ATTLIST projectActionList id    ID     #IMPLIED>
   <!ATTLIST projectActionList root  CDATA  #IMPLIED>

<!-- Condition controlling when list action is applied -->
<!ELEMENT applyWhen (and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches|hardwareIs|hardwareMatches|requirement|preclusion)>

<!ELEMENT and ((and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches|hardwareIs|hardwareMatches|requirement|preclusion)*) >
<!ELEMENT or  ((and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches|hardwareIs|hardwareMatches|requirement|preclusion)*) >
<!ELEMENT not  (and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches|hardwareIs|hardwareMatches|requirement|preclusion) >

<!-- Condition controlling when list action is applied -->
<!ELEMENT enableWhen (and|or|not|requirement|preclusion)>

<!-- Allows dynamic checking if a dialogue check-box is selected -->
<!ELEMENT requirement EMPTY >
   <!ATTLIST requirement idRef CDATA #REQUIRED>

<!-- Allows dynamic checking if a dialogue check-box is not selected -->
<!ELEMENT preclusion EMPTY >
   <!ATTLIST preclusion idRef CDATA #REQUIRED>

<!-- Allows testing of a variable -->
<!ELEMENT variableRef EMPTY >
   <!ATTLIST variableRef condition 		(isTrue|isDefined|matches|lessThan|lessThanOrEqual|equal|greaterThan|greaterThanOrEqual) "isTrue">
   <!ATTLIST variableRef idRef         CDATA    #REQUIRED>
   <!ATTLIST variableRef value         CDATA    #IMPLIED>
   <!ATTLIST variableRef defaultValue  CDATA    #IMPLIED>

<!ELEMENT deviceNameIs (#PCDATA) >
<!ELEMENT deviceFamilyIs (#PCDATA) >
<!ELEMENT deviceSubfamilyIs (#PCDATA) >
<!ELEMENT deviceNameMatches (#PCDATA) >
<!ELEMENT deviceFamilyMatches (#PCDATA) >
<!ELEMENT deviceSubfamilyMatches (#PCDATA) >
<!ELEMENT hardwareIs (#PCDATA) >
<!ELEMENT hardwareMatches (#PCDATA) >

<!ELEMENT projectActionListRef EMPTY>
   <!ATTLIST projectActionListRef ref IDREF #REQUIRED>
 
<!-- Variable controlling a block -->
<!ELEMENT variable (enableWhen*) >
   <!ATTLIST variable id           CDATA #REQUIRED>
   <!ATTLIST variable name         CDATA #IMPLIED>
   <!ATTLIST variable description  CDATA #IMPLIED>
   <!ATTLIST variable type         (boolean|int|string) 	"boolean" >
   <!ATTLIST variable defaultValue CDATA #IMPLIED>
   <!ATTLIST variable values       CDATA #IMPLIED>
   <!ATTLIST variable checkGroup   CDATA #IMPLIED>
   <!ATTLIST variable radioGroup   CDATA #IMPLIED>
   
<!ELEMENT constant EMPTY >
   <!ATTLIST constant id           CDATA #REQUIRED>
   <!ATTLIST constant value        CDATA #REQUIRED>
   <!ATTLIST constant type         (boolean|int|string)  "string" >
   <!ATTLIST constant weak         (true|false)          "false">
   <!ATTLIST constant overwrite    (true|false)          "false">
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    (source|include|normal) "normal">

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source                CDATA #REQUIRED>
   <!ATTLIST copy target                CDATA #REQUIRED>
   <!ATTLIST copy type                  CDATA #IMPLIED>
   <!ATTLIST copy sourcePathType        (absolute|relative|unknown) #IMPLIED>
   <!ATTLIST copy macroReplace          (true|false) "true">
   <!ATTLIST copy overwrite             (true|false) "false">
   <!ATTLIST copy derived               (true|false) "false">
   
<!-- Eclipse project options (for gcc, gdb etc) -->
<!ELEMENT projectOption (value*)>
   <!ATTLIST projectOption id        CDATA                #REQUIRED>
   <!ATTLIST projectOption config    (all|release|debug)  "all">
   <!ATTLIST projectOption overwrite (true|false)         "false">

<!-- Custom build action -->
<!ELEMENT customAction (value)* >
   <!ATTLIST customAction class       CDATA #REQUIRED>
   
<!-- Attribute value for projectOption --> 
<!ELEMENT value (#PCDATA)>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/40.CPP-abstraction-FTM.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >
   <projectActionList id="CPP-abstraction-ADC" >
      <applyWhen>
         <and>
            <variableRef idRef="cpp.peripheral.internal.ftm" />
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>

      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.CPP-abstraction" condition="isTrue"/>
         </applyWhen>
   
         <!-- MK ADC CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen>
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MK.*</deviceSubfamilyMatches>
                     </or>
                  </and>
               </applyWhen>
               <copy source="Project_Headers/ftm.h"                              target="Project_Headers/ftm.h" />
               <copy source="Snippets/ftm-pwm-example.cpp"                           target="Snippets/ftm-pwm-example.cpp" />
            </projectActionList>
         </projectActionList>
         
         <!-- MKL ADC CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen>
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MKL.*</deviceSubfamilyMatches>
                        <deviceSubfamilyMatches>MKE.*</deviceSubfamilyMatches>
                     </or>
                  </and>
               </applyWhen>
               <copy source="Project_Headers/ftm.h"                              target="Project_Headers/ftm.h" />
               <copy source="Snippets/ftm-pwm-example.cpp"                           target="Snippets/ftm-pwm-example.cpp" />
            </projectActionList>
         </projectActionList>
         
         <!-- MKM ADC CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen >
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MKM.*</deviceSubfamilyMatches>
                     </or>
                  </and>
               </applyWhen>
            </projectActionList>
         </projectActionList>
      </projectActionList>
   </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/NotUsed/40.CPP-abstraction-PIT.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "package.dtd">

<root version="1.0" >
   <projectActionList id="CPP-abstraction-PIT" >
      <applyWhen>
         <and>
            <variableRef idRef="cpp.peripheral.internal.pit" />
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>

      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.CPP-abstraction" condition="isTrue"/>
         </applyWhen>
         <variable id="projectOptionValue.CPP-abstraction-PIT" 
            name="PIT interface" 
            description="Adds a CPP abstraction layer for Programmable Interrupt Timer hardware" 
            checkGroup="group-peripheral-options" >
         </variable>
   
         <!-- MK PIT CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen>
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MK.*</deviceSubfamilyMatches>
                     </or>
                     <variableRef idRef="projectOptionValue.CPP-abstraction-PIT" />
                  </and>
               </applyWhen>
               <copy source="Snippets/pit-example1.cpp"       target="Snippets/pit-example1.cpp" />
               <copy source="Snippets/pit-example2-MK.cpp"    target="Snippets/pit-example2.cpp" />
               <copy source="Project_Headers/pit-MK.h"        target="Project_Headers/pit.h" />
            </projectActionList>
         </projectActionList>
         
         <!-- MKL PIT CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen>
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MKL.*</deviceSubfamilyMatches>
                        <deviceSubfamilyMatches>MKE.*</deviceSubfamilyMatches>
                     </or>
                     <variableRef idRef="projectOptionValue.CPP-abstraction-PIT" />
                  </and>
               </applyWhen>
               <copy source="Snippets/pit-example1.cpp"       target="Snippets/pit-example1.cpp" />
               <copy source="Snippets/pit-example2-MKL.cpp"   target="Snippets/pit-example2.cpp" />
               <copy source="Project_Headers/pit-MKL.h"        target="Project_Headers/pit.h" />
            </projectActionList>
         </projectActionList>
         
         <!-- MKM PIT CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen >
                  <and>
                     <or>
                        <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
                        <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
                     </or>
                     <or>
                        <deviceSubfamilyMatches>MKM.*</deviceSubfamilyMatches>
                     </or>
                     <variableRef idRef="projectOptionValue.CPP-abstraction-PIT" />
                  </and>
               </applyWhen>
               <copy source="Snippets/pit-example1.cpp"       target="Snippets/pit-example1.cpp" />
               <copy source="Snippets/pit-example2-MKM.cpp"   target="Snippets/pit-example2.cpp" />
               <copy source="Project_Headers/pit-MKM.h"        target="Project_Headers/pit.h" />
               <copy source="Sources/pit-MKM.cpp"              target="Sources/pit.cpp" />
            </projectActionList>
         </projectActionList>
      </projectActionList>
   </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/50.CPP-abstraction-tft-IL9488.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >
   <projectActionList id="CPP-abstraction-TFT-IL9488" >
      <applyWhen>
         <and>
            <or>
               <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM0plus</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
            </or>
            <variableRef idRef="cpp.peripheral.internal.spi" />
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>
      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.CPP-abstraction" condition="isTrue"/>
         </applyWhen>
         <variable id="projectOptionValue.CPP-abstraction-TFT-IL9488"
            name='IL9488 based TFT interface'
            description="Adds a CPP abstraction layer for an IL9488 display"
            checkGroup="group-spi-peripheral-options" >
         </variable>

         <!-- LCD CPP abstraction layer -->
         <projectActionList>
            <projectActionList>
               <applyWhen >
                  <variableRef idRef="projectOptionValue.CPP-abstraction-TFT-IL9488" />
               </applyWhen>
               <copy source="Fonts"                               target="Fonts"                               overwrite="true"/>
               <copy source="Snippets/fonts.h"                    target="Sources/fonts.h"                     overwrite="true"/>
               <copy source="Snippets/tft_IL9488.h"               target="Sources/tft_IL9488.h"                overwrite="true"/>
               <copy source="Snippets/tft-example-IL9488.cpp"     target="Sources/tft-example-IL9488.cpp"      overwrite="true"/>
               <excludeSourceFile target="Sources/tft-example-IL9488.cpp"  />
               <projectOption id="net.sourceforge.usbdm.gnu.c.compiler.option.preprocessor.def.symbols">
                  <value>EPAPER_AVAILABLE</value>
               </projectOption>
               <projectOption id="net.sourceforge.usbdm.gnu.cpp.compiler.option.preprocessor.def.symbols">
                  <value>EPAPER_AVAILABLE</value>
               </projectOption>
            </projectActionList>
         </projectActionList>
      </projectActionList>
    </projectActionList>
</root>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/30.Options-file-list-MKE02Z2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Extra Optional files for MKE02M2 -->
   <projectActionList id="Options-file-list-MKE02Z2">
      <applyWhen>
         <and>
            <deviceSubfamilyIs>MKE02Z2</deviceSubfamilyIs>
            <variableRef idRef="outputType" condition="matches" value=".*ProjectType\.exe$" />
         </and>
      </applyWhen>
      <variable id="projectOptionValue.Clock-setup" 
         name="Clock setup code" 
         description="Adds code for basic clock initialization - check assumptions made"
         checkGroup="group-additional-options"/>
      <variable id="projectOptionValue.UART-setup" 
         name="UART setup code" 
         description="Adds C stdio (UART) support for newlib"          
         checkGroup="group-additional-options" >
         <enableWhen>
            <requirement idRef="projectOptionValue.Clock-setup"/>
         </enableWhen>
      </variable>
      
      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.Clock-setup" />
         </applyWhen>
         <copy source="Startup_Code/clock-MKE0x.c" target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-MKE02M2.h" target="Project_Headers/clock_configure.h" />
      </projectActionList>
      <projectActionList>
         <applyWhen>
            <variableRef idRef="projectOptionValue.UART-setup" />
         </applyWhen>
         <copy source="Startup_Code/console-mke.c" target="Startup_Code/console.c" />
         <copy source="Project_Headers/console.h" target="Project_Headers/console.h" />
      </projectActionList>
   </projectActionList>
</root>
