=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/DeviceData/usbdmDeviceSchema.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Include another file -->
<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>
   <!ATTLIST xi:include parse     (xml|text)   #IMPLIED>

  <!-- Root element -->
<!ELEMENT root (description?,sharedInformation?,(deviceList|xi:include)*) >
  <!ATTLIST root xmlns:xi  CDATA   #IMPLIED>
  <!ATTLIST root version   CDATA   #IMPLIED>

  <!-- General Description element. -->
<!ELEMENT description (#PCDATA)>

  <!-- List of devices -->
<!ELEMENT deviceList (device*)>

  <!-- Device characteristics -->
<!ELEMENT device ((sdid*|
                   (clock?,
                    (resetMethods|resetMethodsRef)?,
                    (eraseMethods|eraseMethodsRef)?,
                    (memory|memoryRef)+,
                    (soptAddress|copctlAddress)?,
                    sdidAddress?,
                    sdidMask?,
                    sdid+,
                    sbdfrAddress?,
                    flashScripts?,
                    (tclScript|tclScriptRef)?,
                    (flashProgram|flashProgramRef)?,
                    flashProgramData?,
                    (flexNVMInfo|flexNVMInfoRef)?,
                    (projectActionList|projectActionListRef)*,
                    (registerDescription|registerDescriptionRef)?
                    )
                   ),
                  note*)>
     <!ATTLIST device name       ID       #REQUIRED>
     <!ATTLIST device alias      IDREF    #IMPLIED>
     <!ATTLIST device family     (RS08|HCS08|HCS08Plus|HCS12|S12Z|CFV1|CFV1Plus|CFV2|CFV3|CFV4|ARM|DSC|CortexM0|CortexM0plus|CortexM3|CortexM3F|CortexM4|CortexM4F) #IMPLIED>
     <!ATTLIST device isDefault  (true)   #IMPLIED>
     <!ATTLIST device speed      CDATA    #IMPLIED>
     <!ATTLIST device subfamily  CDATA    #IMPLIED>
     <!ATTLIST device hidden     (true)   #IMPLIED>
     <!ATTLIST device hardware   CDATA    #IMPLIED>

<!-- List of possible reset modes -->
<!ELEMENT resetMethods (resetMethod*) >
     <!ATTLIST resetMethods id     ID                         #IMPLIED>

<!-- Reference to list of possible reset modes -->
<!ELEMENT resetMethodsRef EMPTY>
     <!ATTLIST resetMethodsRef ref IDREF #REQUIRED>
     
<!-- Available reset modes -->
<!ELEMENT resetMethod EMPTY >
     <!ATTLIST resetMethod method (hardware|software|vendor) #REQUIRED>
     <!ATTLIST resetMethod isDefault  (true)                 #IMPLIED>

  <!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList (projectActionListRef|projectActionList|variable|condition|excludeSourceFile|excludeSourceFolder|createFolder|copy|projectOption|customAction)*>
     <!ATTLIST projectActionList id    ID     #IMPLIED>
     <!ATTLIST projectActionList root  CDATA  #IMPLIED>
     <!ATTLIST isdefault replace           (true|false) #IMPLIED>
     
<!ELEMENT projectActionListRef EMPTY>
     <!ATTLIST projectActionListRef ref IDREF #REQUIRED>
     
<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source  				CDATA #REQUIRED>
   <!ATTLIST copy target  				CDATA #REQUIRED>
   <!ATTLIST copy type    				CDATA #IMPLIED>
   <!ATTLIST copy macroReplacement  (true|false) #IMPLIED>
   <!ATTLIST copy replace           (true|false) #IMPLIED>
   
 <!-- Variable controlling a condition -->
<!ELEMENT variable EMPTY >
     <!ATTLIST variable id           ID    #REQUIRED>
     <!ATTLIST variable name         CDATA #REQUIRED>
     <!ATTLIST variable description  CDATA #IMPLIED>
     <!ATTLIST variable defaultValue CDATA #IMPLIED>
     <!ATTLIST variable type         CDATA #IMPLIED>
     <!ATTLIST variable values       CDATA #IMPLIED>
     <!ATTLIST variable group        CDATA #IMPLIED>
     
 <!-- Custom build action -->
<!ELEMENT customAction (value)* >
     <!ATTLIST customAction class         CDATA #REQUIRED>
     
 <!-- Condition controlling actions -->
<!ELEMENT condition (excludeSourceFile|excludeSourceFolder|createFolder|copy|projectOption|customAction)*>
     <!ATTLIST condition variable    IDREF #REQUIRED>
     <!ATTLIST condition negated    (true) #IMPLIED>
     
<!ELEMENT createFolder EMPTY >
     <!ATTLIST createFolder target  CDATA #REQUIRED>
     <!ATTLIST createFolder type    CDATA #REQUIRED>
     
  <!-- Register description for GDB -->
<!ELEMENT registerDescription  (xi:include)? >
     <!ATTLIST registerDescription id      ID    #IMPLIED>
     <!ATTLIST registerDescription count   CDATA #REQUIRED>

<!ELEMENT registerDescriptionRef EMPTY>
     <!ATTLIST registerDescriptionRef ref IDREF #REQUIRED>

  <!-- Eclipse project options (for gcc, gdb etc) -->
<!ELEMENT projectOption (value*)>
     <!ATTLIST projectOption id        CDATA #REQUIRED>
     <!ATTLIST projectOption replace   (true|false) #IMPLIED>

  <!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
     <!ATTLIST excludeSourceFolder target  CDATA #REQUIRED>
     <!ATTLIST excludeSourceFolder excluded (true|false) #IMPLIED>

  <!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
     <!ATTLIST excludeSourceFile target  CDATA #REQUIRED>
     <!ATTLIST excludeSourceFile excluded (true|false) #IMPLIED>

  <!-- Attribute value for projectOption --> 
<!ELEMENT value (#PCDATA)>  

  <!-- Type of clock & characteristics -->
<!ELEMENT clock EMPTY>
     <!ATTLIST clock type (External|MKEICS|S08ICGV1|S08ICGV2|S08ICGV3|S08ICGV4|S08ICSV1|S08ICSV2|S08ICSV2x512|S08ICSV3|S08ICSV4|RS08ICSOSCV1|RS08ICSV1|S08MCGV1|S08MCGV2|S08MCGV3|MCG_MK) "External">
     <!ATTLIST clock registerAddress CDATA "0" >
  
  <!-- List of memory regions in device -->
<!ELEMENT memory (
     clock?,
     flashProgramRef?,
     (securityEntry|securityEntryRef)?,
     (flexNVMInfo|flexNVMInfoRef)?,
     memoryRange+, 
     (checksumEntry|checksumEntryRef)?,
     description?)>
     <!ATTLIST memory id               ID #IMPLIED>
     <!ATTLIST memory type             (ram|rom|flash|pFlash|dFlash|eeprom|flexNVM|flexRAM|io|pRAM|pROM|xRAM|xROM|bitband) #REQUIRED>
     <!ATTLIST memory subType          CDATA "1">
     <!ATTLIST memory pageAddress      CDATA "0">
     <!ATTLIST memory registerAddress  CDATA "0">
     <!ATTLIST memory securityAddress  CDATA "0">
     <!ATTLIST memory alignment        CDATA #IMPLIED >
     <!ATTLIST memory sectorSize       CDATA #IMPLIED >
	  <!ATTLIST memory addressMode      (linear|paged) #IMPLIED>

<!-- List of possible erase methods -->
<!ELEMENT eraseMethods (eraseMethod)+ >
     <!ATTLIST eraseMethods id     ID   #IMPLIED>
     
<!-- Reference to list of possible erase methods -->
<!ELEMENT eraseMethodsRef EMPTY>
     <!ATTLIST eraseMethodsRef ref IDREF #REQUIRED>
     
<!-- Possible erase methods -->
<!ELEMENT eraseMethod EMPTY>
     <!ATTLIST eraseMethod method (Mass|All|Selective) #REQUIRED>
     <!ATTLIST eraseMethod isDefault  (true)           #IMPLIED> 
     
  <!-- Reference to a list of memory regions in device -->
<!ELEMENT memoryRef EMPTY>
     <!ATTLIST memoryRef ref IDREF #REQUIRED>

  <!-- Checksum Element -->
<!ELEMENT checksumEntry EMPTY >
     <!ATTLIST checksumEntry id           ID                     #IMPLIED>
     <!ATTLIST checksumEntry start        CDATA                  #REQUIRED>   <!-- Start element address -->
     <!ATTLIST checksumEntry end          CDATA                  #REQUIRED>   <!-- End element address -->
     <!ATTLIST checksumEntry location     CDATA                  #REQUIRED>   <!-- Location to write checksum to -->
     <!ATTLIST checksumEntry type         (twoComplementWordSum) #REQUIRED>   <!-- Type of checksum -->

  <!-- Reference to a security Element -->
<!ELEMENT checksumEntryRef EMPTY>
     <!ATTLIST checksumEntryRef ref IDREF #REQUIRED>

  <!-- Security Element -->
<!ELEMENT securityEntry (securityDescription,securityInfo+)>
     <!ATTLIST securityEntry flavour    CDATA "common">
     <!ATTLIST securityEntry id         ID #IMPLIED>

  <!-- Reference to a security Element -->
<!ELEMENT securityEntryRef EMPTY>
     <!ATTLIST securityEntryRef ref IDREF #REQUIRED>

  <!-- Security Information -->
<!ELEMENT securityInfo (#PCDATA)>
     <!ATTLIST securityInfo id      ID #IMPLIED>
     <!ATTLIST securityInfo size    CDATA #REQUIRED>
     <!ATTLIST securityInfo type    (secure|unsecure|custom|lpcChecksum) #REQUIRED>

  <!-- Security Description -->
<!ELEMENT securityDescription (#PCDATA)>
     <!ATTLIST securityDescription id   ID #IMPLIED>

  <!-- Refernce to a security Description -->
<!ELEMENT securityDescriptionRef EMPTY>
     <!ATTLIST securityDescriptionRef ref IDREF #REQUIRED>

  <!-- Reference to a security Information -->
<!ELEMENT securityInfoRef EMPTY>
     <!ATTLIST securityInfoRef ref IDREF #REQUIRED>

  <!-- SOPT address -->
<!ELEMENT soptAddress EMPTY>
     <!ATTLIST soptAddress value CDATA #REQUIRED>

  <!-- SDID address -->
<!ELEMENT sdidAddress EMPTY>
     <!ATTLIST sdidAddress value CDATA #REQUIRED>

  <!--SBDFR address -->
<!ELEMENT sbdfrAddress EMPTY>
     <!ATTLIST sbdfrAddress value CDATA #REQUIRED>

  <!--SDID mask for device significant bits -->
<!ELEMENT sdidMask EMPTY>
     <!ATTLIST sdidMask value CDATA #REQUIRED>

  <!-- Device SDID used to identify device -->
<!ELEMENT sdid EMPTY>
     <!ATTLIST sdid value CDATA #REQUIRED>
     <!ATTLIST sdid mask  CDATA #IMPLIED>

  <!--NVOPT memory address-->
<!ELEMENT nvoptAddress EMPTY>
     <!ATTLIST nvoptAddress value CDATA #REQUIRED>

  <!-- NVSEC memory address -->
<!ELEMENT nvsecAddress EMPTY>
     <!ATTLIST nvsecAddress value CDATA #REQUIRED>

  <!--COPTCTL register address-->
<!ELEMENT copctlAddress EMPTY>
     <!ATTLIST copctlAddress value CDATA #REQUIRED>

  <!--Flash utility functions-->
<!ELEMENT flashScripts (tclScriptRef|tclScript)*>

  <!--Specifies a memory range-->
<!ELEMENT memoryRange (#PCDATA)>
     <!ATTLIST memoryRange name      CDATA #IMPLIED>
     <!-- Various combinations may be used. Addresses are inclusive
     start  + end
     start  + size
     middle + size
     end    + size
     -->
     <!ATTLIST memoryRange start     CDATA #IMPLIED>
     <!ATTLIST memoryRange middle    CDATA #IMPLIED>
     <!ATTLIST memoryRange end       CDATA #IMPLIED>
     <!ATTLIST memoryRange size      CDATA #IMPLIED>
     <!-- Various combinations may be used. pageStart,pageEnd are inclusive
     pageStart  + pageEnd
     pageStart  + pages
     pageEnd    + pages
     pageReset specifies the reset page number
     pageNo    specifies the page number for a single page
     -->
     <!ATTLIST memoryRange pageNo    CDATA #IMPLIED>
     <!ATTLIST memoryRange pageStart CDATA #IMPLIED>
     <!ATTLIST memoryRange pageEnd   CDATA #IMPLIED>
     <!ATTLIST memoryRange pages     CDATA #IMPLIED>
     <!ATTLIST memoryRange pageReset CDATA #IMPLIED>

  <!-- Note on device entry -->
<!ELEMENT note (#PCDATA)>

  <!-- Information shared between devices -->
<!ELEMENT sharedInformation 
	(resetMethods|eraseMethods|memory|tclScript|flashProgram|securityEntry|securityDescription|securityInfo|checksumEntry|flexNVMInfo|projectActionList|registerDescription)*>

  <!--TCL Script-->
<!ELEMENT tclScript (xi:include) >
     <!ATTLIST tclScript id        ID      #IMPLIED>

  <!--Reference to TCL Script-->
<!ELEMENT tclScriptRef EMPTY>
     <!ATTLIST tclScriptRef ref IDREF #REQUIRED>

  <!--Flash program-->
<!ELEMENT flashProgram (xi:include) >
     <!ATTLIST flashProgram id ID #REQUIRED>

  <!--Reference to Flash program-->
<!ELEMENT flashProgramRef EMPTY>
     <!ATTLIST flashProgramRef ref IDREF #REQUIRED>

  <!-- Flasg program data -->
<!ELEMENT flashProgramData (#PCDATA)>

  <!--Partitioning of FlexNVM-->
<!ELEMENT flexNVMInfo (eeepromEntry+, partitionEntry+)>
     <!ATTLIST flexNVMInfo id ID #IMPLIED>
     <!ATTLIST flexNVMInfo backingRatio CDATA "16">

  <!-- EEPROM entry -->
<!ELEMENT eeepromEntry EMPTY>
     <!ATTLIST eeepromEntry description CDATA "">
     <!ATTLIST eeepromEntry eeeSize     CDATA "0x00">
     <!ATTLIST eeepromEntry value       CDATA "0x00">

  <!-- Partition Entry -->
<!ELEMENT partitionEntry EMPTY>
     <!ATTLIST partitionEntry description   CDATA "">
     <!ATTLIST partitionEntry eeSize        CDATA "0x00">
     <!ATTLIST partitionEntry value         CDATA "0x00">

  <!-- Flex NVM entry -->
<!ELEMENT flexNVMInfoRef EMPTY>
     <!ATTLIST flexNVMInfoRef ref IDREF #REQUIRED>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/DeviceData/rs08_devices.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE DeviceList SYSTEM "usbdmDeviceSchema.dtd" >

<!--
      V4.10.4 - Changed how security information is expressed
 -->
<root xmlns:xi="http://www.w3.org/2001/XInclude" version="4.12.1.180">
   <description>RS08 Device characteristics v4.8.0 5/12/2011</description>
   <sharedInformation>

      <tclScript id="RS08-default-Scripts">
         <xi:include href="RS08/RS08-default-flash-scripts.tcl" parse="text"/>
      </tclScript>

      <!--
            Security Values for Flash
      -->
      <securityEntry id="RS08-default-security">
         <securityDescription id="RS08-default-security-description">
            NVOPT = [RES=%7b, SECD=%1b]
         </securityDescription>
         <!-- RS08 Unsecured value = NVOPT -->
         <securityInfo size="1" type="unsecure" id="RS08-default-security-off">
            FF
         </securityInfo>
         <!-- RS08 Secured value = NVOPT -->
         <securityInfo size="1" type="secure" id="RS08-default-security-on">
            FE
         </securityInfo>
      </securityEntry>

      <resetMethods id="rs08ResetMethods" >
         <resetMethod method="hardware" />
         <resetMethod method="software" isDefault="true" />
      </resetMethods>

      <eraseMethods id="rs08EraseMethods" >
         <eraseMethod method="Mass" isDefault="true"  />
         <eraseMethod method="All" />
         <eraseMethod method="Selective" />
      </eraseMethods>
   </sharedInformation>

   <deviceList>
<!-- ===================================================================================== -->
<!--
   RS08 Defaults
-->
      <device name="rs08DefaultDevice"  family="RS08" isDefault="true" >
         <clock type="External" />
         <resetMethodsRef ref="rs08ResetMethods" />
         <eraseMethodsRef ref="rs08EraseMethods" />
         <memory type="ram">
            <memoryRange end="0x004F" start="0x0020" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x3C00" />
         </memory>
         <sdidAddress value="0x206" />
         <sdidMask value="0xFFF" />
         <sdid value="0x0" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Default RS08 Device</note>
      </device>
      <device family="RS08" name="MC9RS08KA1">
         <clock registerAddress="0x0014" type="RS08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x004F" start="0x0020" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x3C00" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x800" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
      </device>
      <device family="RS08" name="MC9RS08KA2">
         <clock registerAddress="0x0014" type="RS08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x004F" start="0x0020" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x3800" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x800" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KA4">
         <clock registerAddress="0x023C" type="RS08ICSOSCV1" />
         <memory type="ram">
            <memoryRange end="0x009F" start="0x0030" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x3000" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x803" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KA8">
         <clock registerAddress="0x023C" type="RS08ICSOSCV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0030" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x2000" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x803" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
      </device>
      <device family="RS08" name="MC9RS08KB2">
         <clock registerAddress="0x0238" type="S08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x208" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x3800" />
         </memory>
         <soptAddress value="0x211" />
         <sdidAddress value="0x216" />
         <sdid value="0x806" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KB4">
         <clock registerAddress="0x0238" type="S08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x208" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x3000" />
         </memory>
         <soptAddress value="0x211" />
         <sdidAddress value="0x216" />
         <sdid value="0x806" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KB8">
         <clock registerAddress="0x0238" type="S08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x208" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x2000" />
         </memory>
         <soptAddress value="0x211" />
         <sdidAddress value="0x216" />
         <sdid value="0x806" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KB12">
         <clock registerAddress="0x0238" type="S08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x208" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x1000" />
         </memory>
         <soptAddress value="0x211" />
         <sdidAddress value="0x216" />
         <sdid value="0x806" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08LA8">
         <clock registerAddress="0x022C" type="RS08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x250" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x2000" />
         </memory>
         <soptAddress value="0x019" />
         <sdidAddress value="0x216" />
         <sdid value="0x804" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
      </device>
      <device family="RS08" name="MC9RS08LE4">
         <clock registerAddress="0x022C" type="S08ICSV2x512" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x23C" type="flash" securityAddress="0x3FFC">
            <securityEntryRef ref="RS08-default-security" />
            <memoryRange end="0x3FFF" start="0x3000" />
         </memory>
         <soptAddress value="0x019" />
         <sdidAddress value="0x21A" />
         <sdid value="0x805" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
      </device>
   </deviceList>
</root>
