=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/_menu.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % gui_items        "(xi:include|category|indexedCategory|constant|floatOption|intOption|bitmaskOption|choiceOption|binaryOption|irqOption|stringOption|numericListOption|pinListOption|aliasOption|signals)" >
<!ENTITY % structure_items  "(xi:include|section|list)" >
<!ENTITY % control_items    "(xi:include|template|validate|projectActionList)" >

<!-- Include another file -->
<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>

<!-- Root fileElement -->
<!ELEMENT peripheralPage ((%structure_items;|%gui_items;|%control_items;)*) >
   <!ATTLIST peripheralPage xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST peripheralPage name         CDATA        #REQUIRED>
   <!ATTLIST peripheralPage description  CDATA        #REQUIRED>
   <!ATTLIST peripheralPage toolTip      CDATA        #IMPLIED>

<!ELEMENT fragment ANY >
   <!ATTLIST fragment xmlns:xi CDATA #IMPLIED>

<!ELEMENT list (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST list name         CDATA        #IMPLIED>
   <!ATTLIST list description  CDATA        #IMPLIED>

<!ELEMENT section (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST section name         CDATA        #IMPLIED>

<!ELEMENT indexedCategory ((%gui_items;)*) >
   <!ATTLIST indexedCategory xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST indexedCategory name         ID           #REQUIRED>
   <!ATTLIST indexedCategory description  CDATA        #REQUIRED>
   <!ATTLIST indexedCategory toolTip      CDATA        #IMPLIED>
   <!ATTLIST indexedCategory dim          CDATA        #REQUIRED>
   <!ATTLIST indexedCategory value        CDATA        #IMPLIED>
   <!ATTLIST indexedCategory constant     (false|true) #IMPLIED>

<!ELEMENT category ((%gui_items;|template)*) >
   <!ATTLIST category  constant     (false|true) #IMPLIED>
   <!ATTLIST category  xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST category  name         CDATA        #REQUIRED>
   <!ATTLIST category  key          CDATA        #IMPLIED>
   <!ATTLIST category  description  CDATA        #REQUIRED>
   <!ATTLIST category  toolTip      CDATA        #IMPLIED>
   <!ATTLIST category  derived      (false|true) #IMPLIED>

<!ELEMENT intOption (for?) >
   <!ATTLIST intOption constant     (false|true)  #IMPLIED>
   <!ATTLIST intOption hidden       (false|true)  #IMPLIED>
   <!ATTLIST intOption name          ID           #REQUIRED>
   <!ATTLIST intOption key           CDATA        #IMPLIED>
   <!ATTLIST intOption origin        CDATA        #IMPLIED>
   <!ATTLIST intOption description   CDATA        #IMPLIED>
   <!ATTLIST intOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST intOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST intOption value         CDATA        #IMPLIED>
   <!ATTLIST intOption units         (None|Hz|s)  #IMPLIED>
   <!ATTLIST intOption step          CDATA        "1">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST intOption min           CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST intOption max           CDATA        #IMPLIED>
   <!-- Offset to translate from displayed value to substitution value -->
   <!ATTLIST intOption offset        CDATA        #IMPLIED>
   <!ATTLIST intOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST intOption derived       (false|true) #IMPLIED>
   <!ATTLIST intOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT bitmaskOption EMPTY >
   <!ATTLIST bitmaskOption constant       (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption hidden         (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption name           ID           #REQUIRED>
   <!ATTLIST bitmaskOption key            CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption origin         CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption description    CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption toolTip        CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption value          CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption disabledValue  CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption bitmask        CDATA        "0xFFFF">
   <!ATTLIST bitmaskOption bitList        CDATA        "">
   <!ATTLIST bitmaskOption indexedBy      CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption derived        (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption derivedFrom    IDREF        #IMPLIED>
  
<!ELEMENT floatOption (for?) >
   <!ATTLIST floatOption constant      (false|true) #IMPLIED>
   <!ATTLIST floatOption hidden        (false|true) #IMPLIED>
   <!ATTLIST floatOption name          ID           #REQUIRED>
   <!ATTLIST floatOption key           CDATA        #IMPLIED>
   <!ATTLIST floatOption origin        CDATA        #IMPLIED>
   <!ATTLIST floatOption description   CDATA        #IMPLIED>
   <!ATTLIST floatOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST floatOption value         CDATA        #IMPLIED>
   <!ATTLIST floatOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST floatOption units         (None|Hz|s)  #IMPLIED>
   <!-- Minimum value (displayed value) -->
   <!ATTLIST floatOption min           CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST floatOption max           CDATA        #IMPLIED>
   <!ATTLIST floatOption derived       (false|true) #IMPLIED>
   <!ATTLIST floatOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT aliasOption EMPTY >
   <!-- alias Option 
   name 		Refers to another option within the same file and will be used as key and validated as a reference to an ID
   key  		Allows reference to an option (possibly) in another file while passing validation
   displayName	Allows the name of the model (visible in the GUI) to differ from the aliased option's name
   -->
   <!ATTLIST aliasOption name        IDREF        #IMPLIED>
   <!ATTLIST aliasOption key         CDATA        #IMPLIED>
   <!ATTLIST aliasOption displayName CDATA        #IMPLIED>
   <!ATTLIST aliasOption description CDATA        #IMPLIED>
   <!ATTLIST aliasOption toolTip     CDATA        #IMPLIED>
   <!ATTLIST aliasOption constant    (false|true) "true">
   <!ATTLIST aliasOption optional    (false|true) #IMPLIED>

<!ELEMENT stringOption (for?) >
   <!ATTLIST stringOption constant      (false|true) #IMPLIED>
   <!ATTLIST binaryOption hidden        (false|true) #IMPLIED>
   <!ATTLIST stringOption name          ID           #REQUIRED>
   <!ATTLIST stringOption key           CDATA        #IMPLIED>
   <!ATTLIST stringOption origin        CDATA        #IMPLIED>
   <!ATTLIST stringOption description   CDATA        #IMPLIED>
   <!ATTLIST stringOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST stringOption value         CDATA        #IMPLIED>
   <!ATTLIST stringOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST stringOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST stringOption derived       (false|true) #IMPLIED>
   <!ATTLIST stringOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT numericListOption (for?) >
   <!ATTLIST numericListOption constant      (false|true) #IMPLIED>
   <!ATTLIST numericListOption hidden        (false|true) #IMPLIED>
   <!ATTLIST numericListOption name          ID           #REQUIRED>
   <!ATTLIST numericListOption key           CDATA        #IMPLIED>
   <!ATTLIST numericListOption origin        CDATA        #IMPLIED>
   <!ATTLIST numericListOption description   CDATA        #IMPLIED>
   <!ATTLIST numericListOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST numericListOption value         CDATA        #IMPLIED>
   <!ATTLIST numericListOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST numericListOption size          CDATA        #IMPLIED>
   <!ATTLIST numericListOption min           CDATA        #IMPLIED>
   <!ATTLIST numericListOption max           CDATA        #IMPLIED>
   <!ATTLIST numericListOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST numericListOption derived       (false|true) #IMPLIED>
   <!ATTLIST numericListOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT pinListOption (for?) >
   <!ATTLIST pinListOption constant      (false|true) #IMPLIED>
   <!ATTLIST pinListOption hidden        (false|true) #IMPLIED>
   <!ATTLIST pinListOption name          ID           #REQUIRED>
   <!ATTLIST pinListOption key           CDATA        #IMPLIED>
   <!ATTLIST pinListOption origin        CDATA        #IMPLIED>
   <!ATTLIST pinListOption description   CDATA        #IMPLIED>
   <!ATTLIST pinListOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST pinListOption value         CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST pinListOption size          CDATA        #IMPLIED>
   <!ATTLIST pinListOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST pinListOption derived       (false|true) #IMPLIED>
   <!ATTLIST pinListOption derivedFrom   IDREF        #IMPLIED>
   
<!ELEMENT choiceOption (for?, (choice)*) >
   <!ATTLIST choiceOption constant            (false|true) #IMPLIED>
   <!ATTLIST choiceOption hidden              (false|true) #IMPLIED>
   <!ATTLIST choiceOption name                ID           #IMPLIED>
   <!ATTLIST choiceOption key                 CDATA        #IMPLIED>
   <!ATTLIST choiceOption origin              CDATA        #IMPLIED>
   <!ATTLIST choiceOption description         CDATA        #IMPLIED>
   <!ATTLIST choiceOption toolTip             CDATA        #IMPLIED>
   <!ATTLIST choiceOption units               (None|Hz|s)  #IMPLIED>
   <!ATTLIST choiceOption indexedBy           CDATA        #IMPLIED>
   <!ATTLIST choiceOption derived             (false|true) #IMPLIED>
   <!ATTLIST choiceOption derivedFrom         IDREF        #IMPLIED>
  
<!ELEMENT choice EMPTY >
   <!ATTLIST choice value                     CDATA        #REQUIRED>
   <!ATTLIST choice name                      CDATA        #REQUIRED>
   <!ATTLIST choice requiresPeripheral        CDATA        #IMPLIED>
   <!ATTLIST choice isDefault                 (false|true) #IMPLIED>

<!ELEMENT binaryOption (for?, choice, choice)? >
   <!ATTLIST binaryOption constant      (false|true) #IMPLIED>
   <!ATTLIST binaryOption hidden        (false|true) #IMPLIED>
   <!ATTLIST binaryOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST binaryOption name          ID           #IMPLIED>
   <!ATTLIST binaryOption key           CDATA        #IMPLIED>
   <!ATTLIST binaryOption origin        CDATA        #IMPLIED>
   <!ATTLIST binaryOption description   CDATA        #IMPLIED>
   <!ATTLIST binaryOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST binaryOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST binaryOption derived       (false|true) #IMPLIED>
   <!ATTLIST binaryOption derivedFrom   IDREF        #IMPLIED>

<!ELEMENT irqOption EMPTY >
   <!ATTLIST irqOption constant      (false|true) #IMPLIED>
   <!ATTLIST irqOption hidden        (false|true) #IMPLIED>
   <!ATTLIST irqOption name          ID           #REQUIRED>
   <!ATTLIST irqOption key           CDATA        #IMPLIED>
   <!ATTLIST irqOption pattern       CDATA        #REQUIRED>
   <!ATTLIST irqOption classHandler  CDATA        #REQUIRED>
   <!ATTLIST irqOption value         CDATA        #IMPLIED>
   <!ATTLIST irqOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST irqOption origin        CDATA        #IMPLIED>
   <!ATTLIST irqOption description   CDATA        #IMPLIED>
   <!ATTLIST irqOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST irqOption derived       (false|true) #IMPLIED>
   <!ATTLIST irqOption derivedFrom   IDREF        #IMPLIED>

<!ELEMENT template (#PCDATA|for)* >
   <!ATTLIST template namespace (info|usbdm|class|all)  "info" >
   <!ATTLIST template name 		CDATA  					"" >
   <!ATTLIST template dim  		CDATA  					"0" >

<!ELEMENT for (#PCDATA|for)* >
   <!ATTLIST for var         CDATA #REQUIRED >
   <!ATTLIST for enumeration CDATA #REQUIRED >

<!ELEMENT validate (param*) >
   <!ATTLIST validate class CDATA #REQUIRED>
   <!ATTLIST validate dim  		   CDATA        "0" >
   
<!ELEMENT param EMPTY >
   <!ATTLIST param type  (long|string) #REQUIRED>
   <!ATTLIST param value CDATA         #REQUIRED>

<!ELEMENT signals EMPTY >
   <!ATTLIST signals name        CDATA "" >
   <!ATTLIST signals optional    (false|true) #IMPLIED>

<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList ((deleteResource|copy|constant)*) >
   <!ATTLIST projectActionList id          ID            #REQUIRED>
   <!ATTLIST projectActionList root        CDATA         #IMPLIED>
   <!ATTLIST projectActionList doOnceOnly  (true|false)  "true">
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    (source|include|normal) "normal">

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source               CDATA #REQUIRED>
   <!ATTLIST copy target               CDATA #REQUIRED>
   <!ATTLIST copy type                 CDATA #IMPLIED>
   <!ATTLIST copy sourcePathType       (absolute|relative|unknown) #IMPLIED>
   <!ATTLIST copy macroReplace         (true|false) "true">
   <!ATTLIST copy overwrite            (true|false) #IMPLIED>
   <!ATTLIST copy derived              (true|false) #IMPLIED>
   
<!ELEMENT constant EMPTY >
   <!-- constant 
   key       Allows specification of a explicit key rather than based upon the name.
   name      In the absence of a key it is used to create a key tied to the current peripheral/file. 
             Used as visible name in GUI (model)
             Supports validation as an ID.
   weak	     If true indicates the constant may already exist and this constant is discarded
   overwrite Replaces any existing constant of the same key
   -->
   <!ATTLIST constant name         ID           #IMPLIED>
   <!ATTLIST constant key          CDATA        #IMPLIED>
   <!ATTLIST constant value        CDATA        #REQUIRED>
   <!ATTLIST constant type         (boolean|int|string)  "string" >
   <!ATTLIST constant weak         (true|false)          #IMPLIED>
   <!ATTLIST constant replace      (true|false)          #IMPLIED>
   <!ATTLIST constant derived      (true|false)          #IMPLIED>
   
<!ELEMENT divider EMPTY >

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/mcg_mkl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- mgc_mkl.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Multipurpose Clock Generator">

   <indexedCategory name="DummyClockConfig."  dim="/SIM/numberOfClockSettings"
         description="Clock configuration" 
         hidden="true"
         constant="true"
         derived="true"         
         toolTip="Clock configurations for different run modes"
         value="ClockConfig_."  >

      <binaryOption name="mcg_c8_lolre." 
         description="PLL Loss of Lock Reset Enable"
         toolTip="Determines if an interrupt or a reset request is made following a PLL loss of lock.\n
                  Only has an affect when CME1 is set">
         <choice value="0" name="Interrupt request" />
         <choice value="1" name="Reset request" />
      </binaryOption>
      
   </indexedCategory>
   
   <binaryOption name="mcg_c2_erefs0"
      description="External Reference Select" 
      toolTip="Determines whether a clock or crystal is used for the external reference clock"
      hidden="true" >
      <choice value="0" name="External clock" />
      <choice value="1" name="Oscillator" isDefault="true" />
   </binaryOption>
   
   <binaryOption name="mcg_c2_hgo0"
      description="Oscillator Gain" 
      toolTip="Controls the crystal oscillator mode of operation"
      hidden="true" >
      <choice value="0" name="Low power" isDefault="true"/>
      <choice value="1" name="High gain" />
   </binaryOption>
   

   <validate
      class="net.sourceforge.usbdm.deviceEditor.validators.ClockValidator_MCG" dim="/SIM/numberOfClockSettings" >
      <param type="long" value="1" />              <!-- mcg_c4_drst_drs   -->
      <param type="long" value="2000000" />        <!-- pllInMin     -->
      <param type="long" value="4000000" />        <!-- pllInMax     -->
      <param type="long" value="48000000" />       <!-- pllOutMin    -->
      <param type="long" value="120000000" />      <!-- pllOutMax    -->
      <param type="long" value="1" />              <!-- prDivMin     -->
      <param type="long" value="25" />             <!-- prDivMax     -->
      <param type="long" value="24" />             <!-- vDivMin    - available as pll_vdiv_min -->
      <param type="long" value="55" />             <!-- vDivMax      -->
      <param type="long" value="1" />              <!-- pllPostDiv - available as pll_post_divider -->
   </validate>
   
   <xi:include href="mcg_base.xml"/>

   <category name="Hardware bugs" description="">
      <binaryOption name="ERRATA_E2448" 
         description="Flash prefetch could result in incorrect read data"
         toolTip="Issue: Flash prefetch could result in incorrect read data when CLKDIV1 changed\n
         Workaround: Use code in RAM that disables/restores prefetch around changing CLKDIV1" >
         <choice value="0" name="No special handling" />
         <choice value="1" name="Special handing" isdefault="true" />
      </binaryOption>
      <binaryOption name="ERRATA_E7993" 
         description="FLL frequency may be incorrect"
         toolTip="Issue: FLL frequency may be incorrect after changing the FLL reference clock\n
         Workaround: Invert MCG_C4[DMX32] before clock source changes and restore afterwards">
         <choice value="0" name="No special handling" />
         <choice value="1" name="Special handing" isdefault="true" />
      </binaryOption>
   </category>

</peripheralPage>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/_usb_def_clkrcv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- _usb_def_clkrcv.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="USB">

   <xi:include href="_default_instance.xml"/>
   <xi:include href="_mapPinsOption_on.xml"/>

   <aliasOption key="/SIM/system_usb_clkin_clock"     constant="false" optional="true"/>
   
   <for keys="n" dim="/SIM/numberOfClockSettings" >
      <aliasCategoryOption key="/MCG/ClockConfig[%(n)]"           constant="true" >
         <aliasOption key="/SIM/system_peripheral_clock[%(n)]"    constant="true" optional="true"/>
         <aliasOption key="/SIM/sim_sopt2_usbsrc[%(n)]"           constant="false" optional="true"/>
         <aliasOption key="/SIM/sim_clkdiv2_usb[%(n)]"            constant="false" optional="true"/>
         <aliasOption key="/SIM/system_usbfs_clock[%(n)]"         optional="true"/>
      </aliasCategoryOption>
   </for>
   
   <choiceOption key="usb_clk_enable" 
      enumStem="UsbIrc48mClockEnable"
      valueFormat="(%s)"
      description="IRC48M enable"
      toolTip="Enables the IRC48M clock as a clock source for FS USB">
      <choice value="USB_CLK_RECOVER_IRC_EN_IRC_EN(0)"  enum="Peripheral"       name="Not available"  isDefault="true"  />
      <choice value="USB_CLK_RECOVER_IRC_EN_IRC_EN(1)"  enum="PeripheralAndUsb" name="Available as USB clock"  />
   </choiceOption>
      
   <xi:include href="_usb_base_clkrcv.xml"/>

   <xi:include href="_irqOption.xml"/>
   
   <xi:include href="_clockOption.xml"/>
   
   <xi:include href="_usb_base_files.xml"/>

   <signals/>
</peripheralPage>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/llwu_pe2_filt2_base.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- llwu_pe4_filt2_base.xml -->

<fragment xmlns:xi="http://www.w3.org/2001/XInclude">


   <xi:include href="_default_instance.xml"/>
   
   <xi:include href="_mapPinsOption.xml"/>   

   <choiceOption name="llwu_pe1_wupe_t" hidden="true" 
      description="Wakeup Pin Enable" 
      toolTip="Enables and configures the edge detection for the wakeup pin">
      <choice name="Disabled" value="0" isDefault="true" /> 
      <choice name="Rising"   value="1" /> 
      <choice name="Falling"  value="2" /> 
      <choice name="Either"   value="3" />
   </choiceOption>   
   <choiceOption name="llwu_pe1_wupe0" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption name="llwu_pe1_wupe1" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption name="llwu_pe1_wupe2" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption name="llwu_pe1_wupe3" derivedFrom="llwu_pe1_wupe_t"/>

   <template><![CDATA[
      \t// LLWU Pin Enable registers
      \tstatic constexpr uint8_t pe1 = 
      \t   LLWU_PE1_WUPE0($(llwu_pe1_wupe0))|   // LLWUP 0
      \t   LLWU_PE1_WUPE1($(llwu_pe1_wupe1))|   // LLWUP 1
      \t   LLWU_PE1_WUPE2($(llwu_pe1_wupe2))|   // LLWUP 2
      \t   LLWU_PE1_WUPE3($(llwu_pe1_wupe3));   // LLWUP 3 \n\n
   ]]></template>

   <choiceOption name="llwu_pe2_wupe4" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption name="llwu_pe2_wupe5" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption name="llwu_pe2_wupe6" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption name="llwu_pe2_wupe7" derivedFrom="llwu_pe1_wupe_t"/>

   <template><![CDATA[
      \tstatic constexpr uint8_t pe2 = 
      \t   LLWU_PE2_WUPE4($(llwu_pe2_wupe4))|   // LLWUP 4
      \t   LLWU_PE2_WUPE5($(llwu_pe2_wupe5))|   // LLWUP 5
      \t   LLWU_PE2_WUPE6($(llwu_pe2_wupe6))|   // LLWUP 6
      \t   LLWU_PE2_WUPE7($(llwu_pe2_wupe7));   // LLWUP 7 \n\n
   ]]></template>

   <choiceOption 
      name="llwu_filt1_filte" 
      description="Digital Filter 1 On External Pin"  
      toolTip="Controls the digital filter options for the external pin detect.">
      
      <choice name="Filter disabled" value="0" isDefault="true" />
      <choice name="Filter rising"   value="1" />
      <choice name="Filter falling"  value="2" />
      <choice name="Filter both"     value="3" />
   </choiceOption>   
   
   <intOption 
      name="llwu_filt1_filtsel" 
      description="Filter 1 Pin Select" 
      toolTip="Selects 1 of the external signals to be muxed into the filter"
      min="0" max="15" />
      
   <template><![CDATA[
      \t// Pin Filter 1 register
      \tstatic constexpr uint8_t filt1 = 
      \t   LLWU_FILT_FILTE($(llwu_filt1_filte)) |   // Digital Filter On External Pin
      \t   LLWU_FILT_FILTSEL($(llwu_filt1_filtsel));  // Filter Pin Select\n\n
   ]]></template>
      
   <choiceOption 
      name="llwu_filt2_filte" 
      description="Digital Filter 2 On External Pin"  
      toolTip="Controls the digital filter options for the external pin detect.">
      
      <choice name="Filter disabled" value="0" isDefault="true" />
      <choice name="Filter rising"   value="1" />
      <choice name="Filter falling"  value="2" />
      <choice name="Filter both"     value="3" />
   </choiceOption>   
   
   <intOption 
      name="llwu_filt2_filtsel" 
      description="Filter 2 Pin Select" 
      toolTip="Selects 1 of the external signals to be muxed into the filter"
      min="0" max="15" />

   <template><![CDATA[
      \t// Pin Filter 2 register
      \tstatic constexpr uint8_t filt2 =
      \t   LLWU_FILT_FILTE($(llwu_filt2_filte)) |   // Digital Filter On External Pin
      \t   LLWU_FILT_FILTSEL($(llwu_filt2_filtsel));  // Filter Pin Select\n\n
   ]]></template>
      
         
</fragment>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/llwu_pe4_filt2_rst.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- llwu_pe4_filt2_rst.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Low Leakage Wakeup Unit">

   <binaryOption name="llwu_me_wume_t" hidden="true"
      toolTip="Enables this peripheral to wakeup the processor">
      <choice name="Disabled" value="0" isDefault="true" />
      <choice name="Enabled"  value="1" />
   </binaryOption>   
   <binaryOption name="llwu_me_wume0" description="LPTMR"         derivedFrom="llwu_me_wume_t" />
   <binaryOption name="llwu_me_wume1" description="CMP0"          derivedFrom="llwu_me_wume_t" />
   <binaryOption name="llwu_me_wume2" description="CMP1"          derivedFrom="llwu_me_wume_t" />
   <binaryOption name="llwu_me_wume3" description="CMP2/CMP3"     derivedFrom="llwu_me_wume_t" />
   <binaryOption name="llwu_me_wume4" description="TSI0"          derivedFrom="llwu_me_wume_t" />
   <binaryOption name="llwu_me_wume5" description="RTC Alarm"     derivedFrom="llwu_me_wume_t" />
   <binaryOption name="llwu_me_wume7" description="RTC Seconds"   derivedFrom="llwu_me_wume_t" />

   <template><![CDATA[
      \t// Module wake ups
      \tstatic constexpr uint8_t me =  
      \t   LLWU_ME_WUME0($(llwu_me_wume0:0)) |  // LPTMR
      \t   LLWU_ME_WUME1($(llwu_me_wume1:0)) |  // CMP0
      \t   LLWU_ME_WUME2($(llwu_me_wume2:0)) |  // CMP1
      \t   LLWU_ME_WUME3($(llwu_me_wume3:0)) |  // CMP2/3 (if present)
      \t   LLWU_ME_WUME4($(llwu_me_wume4:0)) |  // TSI0 (if present)
      \t   LLWU_ME_WUME5($(llwu_me_wume5:0)) |  // RTC Alarm
      \t   LLWU_ME_WUME6($(llwu_me_wume6:0)) |  //
      \t   LLWU_ME_WUME7($(llwu_me_wume7:0));   // RTC Seconds\n\n
   ]]></template>
      
   <xi:include href="llwu_pe4_filt2_rst_base.xml"/>
      
   <xi:include href="_irqOption.xml"/>

   <validate
      class="net.sourceforge.usbdm.deviceEditor.validators.LlwuValidate">
   </validate>

   <signals/>

   <projectActionList id = "llwu_files" >
      <copy source="Project_Headers/llwu.h"            target="Project_Headers/llwu.h"           overwrite="true" derived="true" />
      <copy source="Snippets/llwu-example-mk20.cpp"    target="Snippets/llwu-example-mk20.cpp"   overwrite="true" derived="true" />
      <copy source="Snippets/llwu-example-mk22f.cpp"   target="Snippets/llwu-example-mk22f.cpp"  overwrite="true" derived="true" />
      <copy source="Snippets/llwu-example-mk28f.cpp"   target="Snippets/llwu-example-mk28f.cpp"  overwrite="true" derived="true" />
      <copy source="Snippets/llwu-example-mkl25z.cpp"  target="Snippets/llwu-example-mkl25z.cpp"  overwrite="true" derived="true" />
   </projectActionList>
         
</peripheralPage>
