=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/_menu.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % gui_items        "(xi:include|category|indexedCategory|constant|floatOption|intOption|bitmaskOption|choiceOption|binaryOption|irqOption|stringOption|numericListOption|pinListOption|aliasOption|signals)" >
<!ENTITY % structure_items  "(xi:include|section|list)" >
<!ENTITY % control_items    "(xi:include|template|validate|projectActionList)" >

<!-- Include another file -->
<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>

<!-- Root fileElement -->
<!ELEMENT peripheralPage ((%structure_items;|%gui_items;|%control_items;)*) >
   <!ATTLIST peripheralPage xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST peripheralPage name         CDATA        #REQUIRED>
   <!ATTLIST peripheralPage description  CDATA        #REQUIRED>
   <!ATTLIST peripheralPage toolTip      CDATA        #IMPLIED>

<!ELEMENT fragment ANY >
   <!ATTLIST fragment xmlns:xi CDATA #IMPLIED>

<!ELEMENT list (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST list name         CDATA        #IMPLIED>
   <!ATTLIST list description  CDATA        #IMPLIED>

<!ELEMENT section (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST section name         CDATA        #IMPLIED>

<!ELEMENT indexedCategory ((%gui_items;)*) >
   <!ATTLIST indexedCategory xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST indexedCategory name         ID           #REQUIRED>
   <!ATTLIST indexedCategory description  CDATA        #REQUIRED>
   <!ATTLIST indexedCategory toolTip      CDATA        #IMPLIED>
   <!ATTLIST indexedCategory dim          CDATA        #REQUIRED>
   <!ATTLIST indexedCategory value        CDATA        #IMPLIED>
   <!ATTLIST indexedCategory constant     (false|true) #IMPLIED>

<!ELEMENT category ((%gui_items;|template)*) >
   <!ATTLIST category  constant     (false|true) #IMPLIED>
   <!ATTLIST category  xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST category  name         CDATA        #REQUIRED>
   <!ATTLIST category  key          CDATA        #IMPLIED>
   <!ATTLIST category  description  CDATA        #REQUIRED>
   <!ATTLIST category  toolTip      CDATA        #IMPLIED>
   <!ATTLIST category  derived      (false|true) #IMPLIED>

<!ELEMENT intOption (for?) >
   <!ATTLIST intOption constant     (false|true)  #IMPLIED>
   <!ATTLIST intOption hidden       (false|true)  #IMPLIED>
   <!ATTLIST intOption name          ID           #REQUIRED>
   <!ATTLIST intOption key           CDATA        #IMPLIED>
   <!ATTLIST intOption origin        CDATA        #IMPLIED>
   <!ATTLIST intOption description   CDATA        #IMPLIED>
   <!ATTLIST intOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST intOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST intOption value         CDATA        #IMPLIED>
   <!ATTLIST intOption units         (None|Hz|s)  #IMPLIED>
   <!ATTLIST intOption step          CDATA        "1">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST intOption min           CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST intOption max           CDATA        #IMPLIED>
   <!-- Offset to translate from displayed value to substitution value -->
   <!ATTLIST intOption offset        CDATA        #IMPLIED>
   <!ATTLIST intOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST intOption derived       (false|true) #IMPLIED>
   <!ATTLIST intOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT bitmaskOption EMPTY >
   <!ATTLIST bitmaskOption constant       (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption hidden         (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption name           ID           #REQUIRED>
   <!ATTLIST bitmaskOption key            CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption origin         CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption description    CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption toolTip        CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption value          CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption disabledValue  CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption bitmask        CDATA        "0xFFFF">
   <!ATTLIST bitmaskOption bitList        CDATA        "">
   <!ATTLIST bitmaskOption indexedBy      CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption derived        (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption derivedFrom    IDREF        #IMPLIED>
  
<!ELEMENT floatOption (for?) >
   <!ATTLIST floatOption constant      (false|true) #IMPLIED>
   <!ATTLIST floatOption hidden        (false|true) #IMPLIED>
   <!ATTLIST floatOption name          ID           #REQUIRED>
   <!ATTLIST floatOption key           CDATA        #IMPLIED>
   <!ATTLIST floatOption origin        CDATA        #IMPLIED>
   <!ATTLIST floatOption description   CDATA        #IMPLIED>
   <!ATTLIST floatOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST floatOption value         CDATA        #IMPLIED>
   <!ATTLIST floatOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST floatOption units         (None|Hz|s)  #IMPLIED>
   <!-- Minimum value (displayed value) -->
   <!ATTLIST floatOption min           CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST floatOption max           CDATA        #IMPLIED>
   <!ATTLIST floatOption derived       (false|true) #IMPLIED>
   <!ATTLIST floatOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT aliasOption EMPTY >
   <!-- alias Option 
   name 		Refers to another option within the same file and will be used as key and validated as a reference to an ID
   key  		Allows reference to an option (possibly) in another file while passing validation
   displayName	Allows the name of the model (visible in the GUI) to differ from the aliased option's name
   -->
   <!ATTLIST aliasOption name        IDREF        #IMPLIED>
   <!ATTLIST aliasOption key         CDATA        #IMPLIED>
   <!ATTLIST aliasOption displayName CDATA        #IMPLIED>
   <!ATTLIST aliasOption description CDATA        #IMPLIED>
   <!ATTLIST aliasOption toolTip     CDATA        #IMPLIED>
   <!ATTLIST aliasOption constant    (false|true) "true">
   <!ATTLIST aliasOption optional    (false|true) #IMPLIED>

<!ELEMENT stringOption (for?) >
   <!ATTLIST stringOption constant      (false|true) #IMPLIED>
   <!ATTLIST binaryOption hidden        (false|true) #IMPLIED>
   <!ATTLIST stringOption name          ID           #REQUIRED>
   <!ATTLIST stringOption key           CDATA        #IMPLIED>
   <!ATTLIST stringOption origin        CDATA        #IMPLIED>
   <!ATTLIST stringOption description   CDATA        #IMPLIED>
   <!ATTLIST stringOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST stringOption value         CDATA        #IMPLIED>
   <!ATTLIST stringOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST stringOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST stringOption derived       (false|true) #IMPLIED>
   <!ATTLIST stringOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT numericListOption (for?) >
   <!ATTLIST numericListOption constant      (false|true) #IMPLIED>
   <!ATTLIST numericListOption hidden        (false|true) #IMPLIED>
   <!ATTLIST numericListOption name          ID           #REQUIRED>
   <!ATTLIST numericListOption key           CDATA        #IMPLIED>
   <!ATTLIST numericListOption origin        CDATA        #IMPLIED>
   <!ATTLIST numericListOption description   CDATA        #IMPLIED>
   <!ATTLIST numericListOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST numericListOption value         CDATA        #IMPLIED>
   <!ATTLIST numericListOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST numericListOption size          CDATA        #IMPLIED>
   <!ATTLIST numericListOption min           CDATA        #IMPLIED>
   <!ATTLIST numericListOption max           CDATA        #IMPLIED>
   <!ATTLIST numericListOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST numericListOption derived       (false|true) #IMPLIED>
   <!ATTLIST numericListOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT pinListOption (for?) >
   <!ATTLIST pinListOption constant      (false|true) #IMPLIED>
   <!ATTLIST pinListOption hidden        (false|true) #IMPLIED>
   <!ATTLIST pinListOption name          ID           #REQUIRED>
   <!ATTLIST pinListOption key           CDATA        #IMPLIED>
   <!ATTLIST pinListOption origin        CDATA        #IMPLIED>
   <!ATTLIST pinListOption description   CDATA        #IMPLIED>
   <!ATTLIST pinListOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST pinListOption value         CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST pinListOption size          CDATA        #IMPLIED>
   <!ATTLIST pinListOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST pinListOption derived       (false|true) #IMPLIED>
   <!ATTLIST pinListOption derivedFrom   IDREF        #IMPLIED>
   
<!ELEMENT choiceOption (for?, (choice)*) >
   <!ATTLIST choiceOption constant            (false|true) #IMPLIED>
   <!ATTLIST choiceOption hidden              (false|true) #IMPLIED>
   <!ATTLIST choiceOption name                ID           #IMPLIED>
   <!ATTLIST choiceOption key                 CDATA        #IMPLIED>
   <!ATTLIST choiceOption origin              CDATA        #IMPLIED>
   <!ATTLIST choiceOption description         CDATA        #IMPLIED>
   <!ATTLIST choiceOption toolTip             CDATA        #IMPLIED>
   <!ATTLIST choiceOption units               (None|Hz|s)  #IMPLIED>
   <!ATTLIST choiceOption indexedBy           CDATA        #IMPLIED>
   <!ATTLIST choiceOption derived             (false|true) #IMPLIED>
   <!ATTLIST choiceOption derivedFrom         IDREF        #IMPLIED>
  
<!ELEMENT choice EMPTY >
   <!ATTLIST choice value                     CDATA        #REQUIRED>
   <!ATTLIST choice name                      CDATA        #REQUIRED>
   <!ATTLIST choice requiresPeripheral        CDATA        #IMPLIED>
   <!ATTLIST choice isDefault                 (false|true) #IMPLIED>

<!ELEMENT binaryOption (for?, choice, choice)? >
   <!ATTLIST binaryOption constant      (false|true) #IMPLIED>
   <!ATTLIST binaryOption hidden        (false|true) #IMPLIED>
   <!ATTLIST binaryOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST binaryOption name          ID           #IMPLIED>
   <!ATTLIST binaryOption key           CDATA        #IMPLIED>
   <!ATTLIST binaryOption origin        CDATA        #IMPLIED>
   <!ATTLIST binaryOption description   CDATA        #IMPLIED>
   <!ATTLIST binaryOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST binaryOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST binaryOption derived       (false|true) #IMPLIED>
   <!ATTLIST binaryOption derivedFrom   IDREF        #IMPLIED>

<!ELEMENT irqOption EMPTY >
   <!ATTLIST irqOption constant      (false|true) #IMPLIED>
   <!ATTLIST irqOption hidden        (false|true) #IMPLIED>
   <!ATTLIST irqOption name          ID           #REQUIRED>
   <!ATTLIST irqOption key           CDATA        #IMPLIED>
   <!ATTLIST irqOption pattern       CDATA        #REQUIRED>
   <!ATTLIST irqOption classHandler  CDATA        #REQUIRED>
   <!ATTLIST irqOption value         CDATA        #IMPLIED>
   <!ATTLIST irqOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST irqOption origin        CDATA        #IMPLIED>
   <!ATTLIST irqOption description   CDATA        #IMPLIED>
   <!ATTLIST irqOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST irqOption derived       (false|true) #IMPLIED>
   <!ATTLIST irqOption derivedFrom   IDREF        #IMPLIED>

<!ELEMENT template (#PCDATA|for)* >
   <!ATTLIST template namespace (info|usbdm|class|all)  "info" >
   <!ATTLIST template name 		CDATA  					"" >
   <!ATTLIST template dim  		CDATA  					"0" >

<!ELEMENT for (#PCDATA|for)* >
   <!ATTLIST for var         CDATA #REQUIRED >
   <!ATTLIST for enumeration CDATA #REQUIRED >

<!ELEMENT validate (param*) >
   <!ATTLIST validate class CDATA #REQUIRED>
   <!ATTLIST validate dim  		   CDATA        "0" >
   
<!ELEMENT param EMPTY >
   <!ATTLIST param type  (long|string) #REQUIRED>
   <!ATTLIST param value CDATA         #REQUIRED>

<!ELEMENT signals EMPTY >
   <!ATTLIST signals name        CDATA "" >
   <!ATTLIST signals optional    (false|true) #IMPLIED>

<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList ((deleteResource|copy|constant)*) >
   <!ATTLIST projectActionList id          ID            #REQUIRED>
   <!ATTLIST projectActionList root        CDATA         #IMPLIED>
   <!ATTLIST projectActionList doOnceOnly  (true|false)  "true">
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    (source|include|normal) "normal">

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source               CDATA #REQUIRED>
   <!ATTLIST copy target               CDATA #REQUIRED>
   <!ATTLIST copy type                 CDATA #IMPLIED>
   <!ATTLIST copy sourcePathType       (absolute|relative|unknown) #IMPLIED>
   <!ATTLIST copy macroReplace         (true|false) "true">
   <!ATTLIST copy overwrite            (true|false) #IMPLIED>
   <!ATTLIST copy derived              (true|false) #IMPLIED>
   
<!ELEMENT constant EMPTY >
   <!-- constant 
   key       Allows specification of a explicit key rather than based upon the name.
   name      In the absence of a key it is used to create a key tied to the current peripheral/file. 
             Used as visible name in GUI (model)
             Supports validation as an ID.
   weak	     If true indicates the constant may already exist and this constant is discarded
   overwrite Replaces any existing constant of the same key
   -->
   <!ATTLIST constant name         ID           #IMPLIED>
   <!ATTLIST constant key          CDATA        #IMPLIED>
   <!ATTLIST constant value        CDATA        #REQUIRED>
   <!ATTLIST constant type         (boolean|int|string)  "string" >
   <!ATTLIST constant weak         (true|false)          #IMPLIED>
   <!ATTLIST constant replace      (true|false)          #IMPLIED>
   <!ATTLIST constant derived      (true|false)          #IMPLIED>
   
<!ELEMENT divider EMPTY >

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/llwu_base_pe1_2.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE fragment SYSTEM "_menu.dtd" >
<!-- llwu_base_pe1_2.xml -->

<fragment xmlns:xi="http://www.w3.org/2001/XInclude">

   <template namespace="usbdm" ><![CDATA[
      \t/**
      \t * LLWU pin wake-up mode
      \t */
      \tenum LlwuPinMode {
      \t   LlwuPinMode_Disabled    = LLWU_PE1_WUPE0(0)|LLWU_PE1_WUPE1(0)|LLWU_PE1_WUPE2(0)|LLWU_PE1_WUPE3(0), //!< Wake-up by pin change disabled
      \t   LlwuPinMode_RisingEdge  = LLWU_PE1_WUPE0(1)|LLWU_PE1_WUPE1(1)|LLWU_PE1_WUPE2(1)|LLWU_PE1_WUPE3(1), //!< Wake-up on pin rising edge
      \t   LlwuPinMode_FallingEdge = LLWU_PE1_WUPE0(2)|LLWU_PE1_WUPE1(2)|LLWU_PE1_WUPE2(2)|LLWU_PE1_WUPE3(2), //!< Wake-up on pin falling edge
      \t   LlwuPinMode_EitherEdge  = LLWU_PE1_WUPE0(3)|LLWU_PE1_WUPE1(3)|LLWU_PE1_WUPE2(3)|LLWU_PE1_WUPE3(3), //!< Wake-up on pin rising or falling edge
      \t};

      \t/**
      \t * LLWU peripheral wake-up mode
      \t */
      \tenum LlwuPeripheralMode {
      \t   LlwuPeripheralMode_Disabled = false, //!< Wake-up by peripheral disabled
      \t   LlwuPeripheralMode_Enabled  = true,  //!< Wake-up by peripheral enabled
      \t};
      \t\n\n
   ]]></template>

   <template key="llwu_base_init" namespace="all"  ><![CDATA[
      \t   llwu->PE1   = Info::pe1;
      \t   llwu->PE2   = Info::pe2;\n
   ]]></template>
   
   <choiceOption key="llwu_pe1_wupe_t" hidden="true" 
      description="" 
      toolTip="Enables and configures the edge detection for the wakeup pin">
      <choice name="Disabled" value="LlwuPinMode_Disabled" isDefault="true" /> 
      <choice name="Rising"   value="LlwuPinMode_RisingEdge" /> 
      <choice name="Falling"  value="LlwuPinMode_FallingEdge" /> 
      <choice name="Either"   value="LlwuPinMode_EitherEdge" />
   </choiceOption>
      
   <choiceOption key="llwu_pe1_wupe0" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption key="llwu_pe1_wupe1" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption key="llwu_pe1_wupe2" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption key="llwu_pe1_wupe3" derivedFrom="llwu_pe1_wupe_t"/>
   <template><![CDATA[
      \t// LLWU Pin Enable registers
      \tstatic constexpr uint8_t pe1 = 
      \t   /* LLWUP 0 */ (LLWU_PE1_WUPE0_MASK&$(llwu_pe1_wupe0))| // $(llwu_pe1_wupe0.description)
      \t   /* LLWUP 1 */ (LLWU_PE1_WUPE1_MASK&$(llwu_pe1_wupe1))| // $(llwu_pe1_wupe1.description)
      \t   /* LLWUP 2 */ (LLWU_PE1_WUPE2_MASK&$(llwu_pe1_wupe2))| // $(llwu_pe1_wupe2.description)
      \t   /* LLWUP 3 */ (LLWU_PE1_WUPE3_MASK&$(llwu_pe1_wupe3)); // $(llwu_pe1_wupe3.description)\n\n
   ]]></template>

   <choiceOption key="llwu_pe2_wupe4" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption key="llwu_pe2_wupe5" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption key="llwu_pe2_wupe6" derivedFrom="llwu_pe1_wupe_t"/>
   <choiceOption key="llwu_pe2_wupe7" derivedFrom="llwu_pe1_wupe_t"/>
   <template><![CDATA[
      \tstatic constexpr uint8_t pe2 = 
      \t   /* LLWUP 4 */ (LLWU_PE2_WUPE4_MASK&$(llwu_pe2_wupe4))| // $(llwu_pe2_wupe4.description)
      \t   /* LLWUP 5 */ (LLWU_PE2_WUPE5_MASK&$(llwu_pe2_wupe5))| // $(llwu_pe2_wupe5.description)
      \t   /* LLWUP 6 */ (LLWU_PE2_WUPE6_MASK&$(llwu_pe2_wupe6))| // $(llwu_pe2_wupe6.description)
      \t   /* LLWUP 7 */ (LLWU_PE2_WUPE7_MASK&$(llwu_pe2_wupe7)); // $(llwu_pe2_wupe7.description) \n\n
   ]]></template>
         
   <template key="declarations" namespace="all"  ><![CDATA[
   \t/**
   \t * Class representing LLWU
   \t */
   \tclass Llwu : public LlwuBase_T<LlwuInfo> {};
   ]]></template>
   
</fragment>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/osc0_mke.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- osc0_mke.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Oscillator">

   <xi:include href="_default_instance.xml"/>

   <xi:include href="_mapPinsOption.xml"/>

   <binaryOption key="osc_cr_oscen" condition="osc_cr_oscen_present"
      enumStem="OscCrOscen"
      toolTip="Enables the OSC module. The OSC module can also be enabled by the ICS module"
      description="OSC Enable" >
      <choice name="OSC disabled"  value="0" enum="OscDisabled"/>
      <choice name="OSC enabled"   value="1" enum="OscEnabled"/>
   </binaryOption>

   <binaryOption key="osc_cr_oscsten" condition="osc_cr_oscsten_present"
      enumStem="OscCrOscsten"
      toolTip="Controls whether or not the OSC clock remains enabled when MCU enters Stop mode and OSCEN is set.\n
               OSCSTEN has no effect if ICS requests OSC enable"
      description="OSC Enable in Stop mode" >
      <choice name="Disabled in Stop mode"  value="0" enum="DisabledInStopMode"/>
      <choice name="Enabled in Stop mode"   value="1" enum="EnabledInStopMode"/>
   </binaryOption>

   <binaryOption key="osc_cr_oscos" condition="osc_cr_oscos_present"
      enumStem="OscCrOscos"
      toolTip="Selects the output clock of the OSC module"
      description="OSC Output Select" >
      <choice name="External clock source"    value="0" enum="ExternalClockSource"/>
      <choice name="Oscillator clock source"  value="1" enum="OscillatorClockSource"/>
   </binaryOption>

   <binaryOption key="osc_cr_range" condition="osc_cr_range_present"
      enumStem="OscCrRange"
      toolTip="Selects the frequency range for the OSC module"
      description="Frequency Range Select" >
      <choice name="Low range of 32 kHz"     value="0" enum="LowRangeOf32Khz"/>
      <choice name="High range of 4-20 MHz"  value="1" enum="HighRangeOf420Mhz"/>
   </binaryOption>

   <binaryOption key="osc_cr_hgo" condition="osc_cr_hgo_present"
      enumStem="OscCrHgo"
      toolTip="Controls the OSC mode of operation"
      description="High Gain Oscillator Select" >
      <choice name="Low-power mode"  value="0" enum="LowPowerMode"/>
      <choice name="High-gain mode"  value="1" enum="HighGainMode"/>
   </binaryOption>

<!-- Grahic here -->  

   <for keys="field:name"
        values="
      osc_cr_oscen:CrOscen;
      osc_cr_oscsten:CrOscsten;
      osc_cr_oscos:CrOscos;
      osc_cr_range:CrRange;
      osc_cr_hgo:CrHgo">
      <setTemplate variables="%(field)"
      ><![CDATA[
         \t/**
         \t * Set %description
         \t *
         %paramDescription
         \t */
         \tstatic void configure%(name)(%params) {
         \t   %defaultFieldExpression
         \t}\n\n
      ]]></setTemplate>
   </for>

<!--   ========== OSC Init class =============================== -->

   <template key="init_description" namespace="all">
   <![CDATA[
      \t/**
      \t * Class used to do initialisation of the $(_class)
      \t *
      \t * This class has a templated constructor that accepts various values.
      \t *
      \t * @note This constructor may be used to create a const instance in Flash
      \t *
      \t * Example:
      \t * @code
      \t * static const $(_class)::Init init {
      \t *
      \t *   // Setup values
      \t *   OscCrOscen_OscDisabled                    // OSC Enable,
      \t *   OscCrOscsten_DisabledInStopMode           // OSC Enable in Stop mode,
      \t *   OscCrOscos_ExternalClockSource            // OSC Output Select,
      \t *   OscCrRange_LowRangeOf32Khz                // Frequency Range Select,
      \t *   OscCrHgo_LowPowerMode                     // High Gain Oscillator Select,
      \t * };
      \t *
      \t * // Initialise $(_class) from values specified above
      \t * $(_class)::configure(init)
      \t * @endcode
      \t */
   ]]>
   </template>

   <template namespace="usbdm">
   <![CDATA[
      class $(_class)BasicInfo {
      \t
      public:
      \t\n
   ]]>
   </template>

   <template namespace="usbdm">
   <![CDATA[
      $(init_description)
      \tclass Init {
      \t
      \tpublic:
      \t   /**
      \t    * Copy Constructor
      \t    */
      \t   constexpr Init(const Init &other) = default;
      \t
      \t   /**
      \t    * Default Constructor
      \t    */
      \t   constexpr Init() = default;
      \t\n
   ]]>
   </template>

<!--   Member variables -->

   <initialValueTemplate namespace="usbdm"
      variables="osc_cr_oscen,osc_cr_oscsten,osc_cr_oscos,osc_cr_range,osc_cr_hgo"
   ><![CDATA[
      \t   /// Control Register
      \t   uint8_t cr = 0;\n\n
   ]]></initialValueTemplate>

<!--   Configure methods -->

   <template discardRepeats="true" key="/OSC/InitMethod" namespace="all" ><![CDATA[
      \t/**
      \t * Configure OSC from values specified in init
      \t *
      \t * @param init Class containing initialisation values
      \t */
      \tstatic void configure(const typename Info::Init &init) {
      \t   enable();
      \t
      \t   osc->CR    = init.cr;
      \t
      \t   calibrate();
      \t}
      \t
      \t/**
      \t * Configure with default settings.
      \t * Configuration determined from Configure.usbdmProject
      \t */
      \tstatic inline void defaultConfigure() {
      \t
      \t   // Update settings
      \t   configure(Info::DefaultInitValue);
      \t}\n
   ]]></template>

<!--   Constructors -->

   <for keys="r"
      values="
            osc_cr_oscen;
            osc_cr_oscsten;
            osc_cr_oscos;
            osc_cr_range;
            osc_cr_hgo
            ">
      <setTemplate namespace="usbdm"
         variables="%(r)"
         linePadding="xxx">
      <![CDATA[
         \t   /**
         \t    * Constructor for %description
         \t    *
         \t    * @tparam   Types
         \t    * @param    rest
         \t    *
         %comments
         \t    */
         \t   template <typename... Types>
         \t   constexpr Init(%params, Types... rest) : Init(rest...) {
         \t
         \t      %registerName = (%registerName&~%mask) | %paramExpression;
         \t   }
         \t\n
      ]]>
      </setTemplate>
   </for>
<!--   Default Initialisation value -->

   <initialValueTemplate
      separator=","
      terminator=","
      variables="
            osc_cr_oscen,
            osc_cr_oscsten,
            osc_cr_oscos,
            osc_cr_range,
            osc_cr_hgo
         "
   ><![CDATA[
      $(init_description)
      \ttypedef $(_class)BasicInfo::Init Init;
      \t
      \t/**
      \t * Default initialisation value for $(_class)
      \t * This value is created from Configure.usbdmProject settings
      \t */
      \tstatic constexpr Init DefaultInitValue = {%initExpression
      \t};\n\n
   ]]></initialValueTemplate>

   <template namespace="usbdm">
      <![CDATA[
      \t}; // $(_class)::BasicInfo::Init\n\n
   ]]>
   </template>

   <template namespace="usbdm">
      <![CDATA[
      }; // $(_class)::BasicInfo\n\n
   ]]>
   </template>

<signals />

</peripheralPage>
