=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/_menu.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % gui_items        "(xi:include|category|indexedCategory|constant|floatOption|intOption|bitmaskOption|choiceOption|binaryOption|irqOption|stringOption|numericListOption|pinListOption|aliasOption|signals)" >
<!ENTITY % structure_items  "(xi:include|section|list)" >
<!ENTITY % control_items    "(xi:include|template|validate|projectActionList)" >

<!-- Include another file -->
<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>

<!-- Root fileElement -->
<!ELEMENT peripheralPage ((%structure_items;|%gui_items;|%control_items;)*) >
   <!ATTLIST peripheralPage xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST peripheralPage name         CDATA        #REQUIRED>
   <!ATTLIST peripheralPage description  CDATA        #REQUIRED>
   <!ATTLIST peripheralPage toolTip      CDATA        #IMPLIED>

<!ELEMENT fragment ANY >
   <!ATTLIST fragment xmlns:xi CDATA #IMPLIED>

<!ELEMENT list (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST list name         CDATA        #IMPLIED>
   <!ATTLIST list description  CDATA        #IMPLIED>

<!ELEMENT section (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST section name         CDATA        #IMPLIED>

<!ELEMENT indexedCategory ((%gui_items;)*) >
   <!ATTLIST indexedCategory xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST indexedCategory name         ID           #REQUIRED>
   <!ATTLIST indexedCategory description  CDATA        #REQUIRED>
   <!ATTLIST indexedCategory toolTip      CDATA        #IMPLIED>
   <!ATTLIST indexedCategory dim          CDATA        #REQUIRED>
   <!ATTLIST indexedCategory value        CDATA        #IMPLIED>
   <!ATTLIST indexedCategory constant     (false|true) #IMPLIED>

<!ELEMENT category ((%gui_items;|template)*) >
   <!ATTLIST category  constant     (false|true) #IMPLIED>
   <!ATTLIST category  xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST category  name         CDATA        #REQUIRED>
   <!ATTLIST category  key          CDATA        #IMPLIED>
   <!ATTLIST category  description  CDATA        #REQUIRED>
   <!ATTLIST category  toolTip      CDATA        #IMPLIED>
   <!ATTLIST category  derived      (false|true) #IMPLIED>

<!ELEMENT intOption (for?) >
   <!ATTLIST intOption constant     (false|true)  #IMPLIED>
   <!ATTLIST intOption hidden       (false|true)  #IMPLIED>
   <!ATTLIST intOption name          ID           #REQUIRED>
   <!ATTLIST intOption key           CDATA        #IMPLIED>
   <!ATTLIST intOption origin        CDATA        #IMPLIED>
   <!ATTLIST intOption description   CDATA        #IMPLIED>
   <!ATTLIST intOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST intOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST intOption value         CDATA        #IMPLIED>
   <!ATTLIST intOption units         (None|Hz|s)  #IMPLIED>
   <!ATTLIST intOption step          CDATA        "1">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST intOption min           CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST intOption max           CDATA        #IMPLIED>
   <!-- Offset to translate from displayed value to substitution value -->
   <!ATTLIST intOption offset        CDATA        #IMPLIED>
   <!ATTLIST intOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST intOption derived       (false|true) #IMPLIED>
   <!ATTLIST intOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT bitmaskOption EMPTY >
   <!ATTLIST bitmaskOption constant       (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption hidden         (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption name           ID           #REQUIRED>
   <!ATTLIST bitmaskOption key            CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption origin         CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption description    CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption toolTip        CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption value          CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption disabledValue  CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption bitmask        CDATA        "0xFFFF">
   <!ATTLIST bitmaskOption bitList        CDATA        "">
   <!ATTLIST bitmaskOption indexedBy      CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption derived        (false|true) #IMPLIED>
   <!ATTLIST bitmaskOption derivedFrom    IDREF        #IMPLIED>
  
<!ELEMENT floatOption (for?) >
   <!ATTLIST floatOption constant      (false|true) #IMPLIED>
   <!ATTLIST floatOption hidden        (false|true) #IMPLIED>
   <!ATTLIST floatOption name          ID           #REQUIRED>
   <!ATTLIST floatOption key           CDATA        #IMPLIED>
   <!ATTLIST floatOption origin        CDATA        #IMPLIED>
   <!ATTLIST floatOption description   CDATA        #IMPLIED>
   <!ATTLIST floatOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST floatOption value         CDATA        #IMPLIED>
   <!ATTLIST floatOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST floatOption units         (None|Hz|s)  #IMPLIED>
   <!-- Minimum value (displayed value) -->
   <!ATTLIST floatOption min           CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST floatOption max           CDATA        #IMPLIED>
   <!ATTLIST floatOption derived       (false|true) #IMPLIED>
   <!ATTLIST floatOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT aliasOption EMPTY >
   <!-- alias Option 
   name 		Refers to another option within the same file and will be used as key and validated as a reference to an ID
   key  		Allows reference to an option (possibly) in another file while passing validation
   displayName	Allows the name of the model (visible in the GUI) to differ from the aliased option's name
   -->
   <!ATTLIST aliasOption name        IDREF        #IMPLIED>
   <!ATTLIST aliasOption key         CDATA        #IMPLIED>
   <!ATTLIST aliasOption displayName CDATA        #IMPLIED>
   <!ATTLIST aliasOption description CDATA        #IMPLIED>
   <!ATTLIST aliasOption toolTip     CDATA        #IMPLIED>
   <!ATTLIST aliasOption constant    (false|true) "true">
   <!ATTLIST aliasOption optional    (false|true) #IMPLIED>

<!ELEMENT stringOption (for?) >
   <!ATTLIST stringOption constant      (false|true) #IMPLIED>
   <!ATTLIST binaryOption hidden        (false|true) #IMPLIED>
   <!ATTLIST stringOption name          ID           #REQUIRED>
   <!ATTLIST stringOption key           CDATA        #IMPLIED>
   <!ATTLIST stringOption origin        CDATA        #IMPLIED>
   <!ATTLIST stringOption description   CDATA        #IMPLIED>
   <!ATTLIST stringOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST stringOption value         CDATA        #IMPLIED>
   <!ATTLIST stringOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST stringOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST stringOption derived       (false|true) #IMPLIED>
   <!ATTLIST stringOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT numericListOption (for?) >
   <!ATTLIST numericListOption constant      (false|true) #IMPLIED>
   <!ATTLIST numericListOption hidden        (false|true) #IMPLIED>
   <!ATTLIST numericListOption name          ID           #REQUIRED>
   <!ATTLIST numericListOption key           CDATA        #IMPLIED>
   <!ATTLIST numericListOption origin        CDATA        #IMPLIED>
   <!ATTLIST numericListOption description   CDATA        #IMPLIED>
   <!ATTLIST numericListOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST numericListOption value         CDATA        #IMPLIED>
   <!ATTLIST numericListOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST numericListOption size          CDATA        #IMPLIED>
   <!ATTLIST numericListOption min           CDATA        #IMPLIED>
   <!ATTLIST numericListOption max           CDATA        #IMPLIED>
   <!ATTLIST numericListOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST numericListOption derived       (false|true) #IMPLIED>
   <!ATTLIST numericListOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT pinListOption (for?) >
   <!ATTLIST pinListOption constant      (false|true) #IMPLIED>
   <!ATTLIST pinListOption hidden        (false|true) #IMPLIED>
   <!ATTLIST pinListOption name          ID           #REQUIRED>
   <!ATTLIST pinListOption key           CDATA        #IMPLIED>
   <!ATTLIST pinListOption origin        CDATA        #IMPLIED>
   <!ATTLIST pinListOption description   CDATA        #IMPLIED>
   <!ATTLIST pinListOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST pinListOption value         CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST pinListOption size          CDATA        #IMPLIED>
   <!ATTLIST pinListOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST pinListOption derived       (false|true) #IMPLIED>
   <!ATTLIST pinListOption derivedFrom   IDREF        #IMPLIED>
   
<!ELEMENT choiceOption (for?, (choice)*) >
   <!ATTLIST choiceOption constant            (false|true) #IMPLIED>
   <!ATTLIST choiceOption hidden              (false|true) #IMPLIED>
   <!ATTLIST choiceOption name                ID           #IMPLIED>
   <!ATTLIST choiceOption key                 CDATA        #IMPLIED>
   <!ATTLIST choiceOption origin              CDATA        #IMPLIED>
   <!ATTLIST choiceOption description         CDATA        #IMPLIED>
   <!ATTLIST choiceOption toolTip             CDATA        #IMPLIED>
   <!ATTLIST choiceOption units               (None|Hz|s)  #IMPLIED>
   <!ATTLIST choiceOption indexedBy           CDATA        #IMPLIED>
   <!ATTLIST choiceOption derived             (false|true) #IMPLIED>
   <!ATTLIST choiceOption derivedFrom         IDREF        #IMPLIED>
  
<!ELEMENT choice EMPTY >
   <!ATTLIST choice value                     CDATA        #REQUIRED>
   <!ATTLIST choice name                      CDATA        #REQUIRED>
   <!ATTLIST choice requiresPeripheral        CDATA        #IMPLIED>
   <!ATTLIST choice isDefault                 (false|true) #IMPLIED>

<!ELEMENT binaryOption (for?, choice, choice)? >
   <!ATTLIST binaryOption constant      (false|true) #IMPLIED>
   <!ATTLIST binaryOption hidden        (false|true) #IMPLIED>
   <!ATTLIST binaryOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST binaryOption name          ID           #IMPLIED>
   <!ATTLIST binaryOption key           CDATA        #IMPLIED>
   <!ATTLIST binaryOption origin        CDATA        #IMPLIED>
   <!ATTLIST binaryOption description   CDATA        #IMPLIED>
   <!ATTLIST binaryOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST binaryOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST binaryOption derived       (false|true) #IMPLIED>
   <!ATTLIST binaryOption derivedFrom   IDREF        #IMPLIED>

<!ELEMENT irqOption EMPTY >
   <!ATTLIST irqOption constant      (false|true) #IMPLIED>
   <!ATTLIST irqOption hidden        (false|true) #IMPLIED>
   <!ATTLIST irqOption name          ID           #REQUIRED>
   <!ATTLIST irqOption key           CDATA        #IMPLIED>
   <!ATTLIST irqOption pattern       CDATA        #REQUIRED>
   <!ATTLIST irqOption classHandler  CDATA        #REQUIRED>
   <!ATTLIST irqOption value         CDATA        #IMPLIED>
   <!ATTLIST irqOption disabledValue CDATA        #IMPLIED>
   <!ATTLIST irqOption origin        CDATA        #IMPLIED>
   <!ATTLIST irqOption description   CDATA        #IMPLIED>
   <!ATTLIST irqOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST irqOption derived       (false|true) #IMPLIED>
   <!ATTLIST irqOption derivedFrom   IDREF        #IMPLIED>

<!ELEMENT template (#PCDATA|for)* >
   <!ATTLIST template namespace (info|usbdm|class|all)  "info" >
   <!ATTLIST template name 		CDATA  					"" >
   <!ATTLIST template dim  		CDATA  					"0" >

<!ELEMENT for (#PCDATA|for)* >
   <!ATTLIST for var         CDATA #REQUIRED >
   <!ATTLIST for enumeration CDATA #REQUIRED >

<!ELEMENT validate (param*) >
   <!ATTLIST validate class CDATA #REQUIRED>
   <!ATTLIST validate dim  		   CDATA        "0" >
   
<!ELEMENT param EMPTY >
   <!ATTLIST param type  (long|string) #REQUIRED>
   <!ATTLIST param value CDATA         #REQUIRED>

<!ELEMENT signals EMPTY >
   <!ATTLIST signals name        CDATA "" >
   <!ATTLIST signals optional    (false|true) #IMPLIED>

<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList ((deleteResource|copy|constant)*) >
   <!ATTLIST projectActionList id          ID            #REQUIRED>
   <!ATTLIST projectActionList root        CDATA         #IMPLIED>
   <!ATTLIST projectActionList doOnceOnly  (true|false)  "true">
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    (source|include|normal) "normal">

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source               CDATA #REQUIRED>
   <!ATTLIST copy target               CDATA #REQUIRED>
   <!ATTLIST copy type                 CDATA #IMPLIED>
   <!ATTLIST copy sourcePathType       (absolute|relative|unknown) #IMPLIED>
   <!ATTLIST copy macroReplace         (true|false) "true">
   <!ATTLIST copy overwrite            (true|false) #IMPLIED>
   <!ATTLIST copy derived              (true|false) #IMPLIED>
   
<!ELEMENT constant EMPTY >
   <!-- constant 
   key       Allows specification of a explicit key rather than based upon the name.
   name      In the absence of a key it is used to create a key tied to the current peripheral/file. 
             Used as visible name in GUI (model)
             Supports validation as an ID.
   weak	     If true indicates the constant may already exist and this constant is discarded
   overwrite Replaces any existing constant of the same key
   -->
   <!ATTLIST constant name         ID           #IMPLIED>
   <!ATTLIST constant key          CDATA        #IMPLIED>
   <!ATTLIST constant value        CDATA        #REQUIRED>
   <!ATTLIST constant type         (boolean|int|string)  "string" >
   <!ATTLIST constant weak         (true|false)          #IMPLIED>
   <!ATTLIST constant replace      (true|false)          #IMPLIED>
   <!ATTLIST constant derived      (true|false)          #IMPLIED>
   
<!ELEMENT divider EMPTY >

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/adc0_s32k142.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- adc0_s32k142.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Analogue to Digital Converter">

   <xi:include href="_default_instance.xml"/>
   <xi:include href="_mapPinsOption.xml"/>
   
   <choiceOption key="adc_cfg1_adiv" description="Clock Divide Select"
      toolTip="Selects the divide ratio used by the ADC to generate the internal clock ADCK">
      <choice value="0" name="Divide by 1" isDefault="true" />
      <choice value="1" name="Divide by 2" />
      <choice value="2" name="Divide by 4" />
      <choice value="3" name="Divide by 8" />
   </choiceOption>

   <floatOption key="clockFrequency" 
      constant="true"
      description="Frequency of ADC clock"
      toolTip="Determined from clock source and prescaler"
      derived="true"
      units="Hz"/>

   <choiceOption key="adc_cfg1_mode" description="Conversion mode selection"
      toolTip="Selects the ADC resolution mode">
      <choice value="0" name="8-bit single/9-bit differential" />
      <choice value="1" name="12-bit single/13-bit differential" />
      <choice value="2" name="10-bit single/11-bit differential" isDefault="true" />
   </choiceOption>

   <intOption key="adc_cfg2_smplts" description="Sample Time Configuration" 
      toolTip="Selects between different sample times based on the conversion mode selected\n
      Longer sample times are advantageous for high impedance sources and also reduces\n
      power consumption in continuous mode as conversion rate is reduced"
      value="2" min="2" max="256" offset="-1"
      />
      
   <choiceOption key="adc_sc2_refsel" description="Voltage Reference Selection"
      toolTip="Selects the voltage reference source used for conversions">
      <choice value="0" name="VRefH and VRefl" isDefault="true" />
      <choice value="1" name="Gnd and VrefOut(1.2V)" />
      <choice value="2" name="Reserved" />
      <choice value="3" name="Reserved" />
   </choiceOption>

   <binaryOption key="adc_sc2_dmaen" description="DMA Enable"
      toolTip="Enables use of DMA with ADC">
      <choice value="0" name="Disabled" isDefault="true" />
      <choice value="1" name="Enabled" />
   </binaryOption>

   <choiceOption key="adc_sc2_compare" description="Compare function"
      toolTip="Enables comparison of ADC result with CV1 and CV2" >
      <choice value="0" name="Disabled" isDefault="true" />
      <choice value="1" name="ADC &lt; low" />
      <choice value="2" name="ADC &gt;= low" />
      <choice value="3" name="(ADC &lt; low) or (high &lt; ADC)" />
      <choice value="4" name="(low &lt; ADC &lt; high)" />
      <choice value="5" name="(low &lt;= ADC &lt;= high)" />
      <choice value="6" name="(ADC &lt;= low) or (high &lt;= ADC)" />
   </choiceOption>

   <intOption key="low_comparison_value" description="ADC low comparison value" 
      toolTip="Low value for ADC automatic comparison\n
         This value is assumed unsigned"
      min="0" max="0xFFFF"
      />
   
   <intOption key="high_comparison_value" description="ADC high comparison value" 
      toolTip="High value for ADC automatic comparison\n
         This value is assumed unsigned"
      min="0" max="0xFFFF"
      />
   
   <intOption key="adc_cv1" description="ADC CV1 value" 
      toolTip="CV1 threshold value\n
         Either low or high value" 
      constant="true" 
      derived="true" />
   <intOption key="adc_cv2" description="ADC CV2 value" 
      toolTip="CV2 threshold value\n
         Either low or high value"  
      constant="true" 
      derived="true" />
   
   <intOption key="adc_sc2_acfe"  description="Compare Function Enable"               
      toolTip="Enable comparison" 
      constant="true" 
      derived="true" />
   <intOption key="adc_sc2_acfgt" description="Compare Function Greater Than Enable"  
      toolTip="Greater-than enable" 
      constant="true" 
      derived="true" />
   <intOption key="adc_sc2_acren" description="Compare Function Range Enable"         
      toolTip="Compare using range" 
      constant="true" 
      derived="true" />
   
   <binaryOption key="adc_sc2_adtrg" description="Conversion Trigger Select"
      toolTip="Selects the type of trigger used for initiating a conversion">
      <choice value="0" name="Software trigger (write to SC1A)" isDefault="true" />
      <choice value="1" name="Hardware trigger (ADHWT source)" />
   </binaryOption>
   
   <category name="Advanced" description="Advanced Options" >
      <aliasOption key="/SIM/sim_sopt7_adc$(_instance)alttrgen"  constant="false" optional="true" />
      <aliasOption key="/SIM/sim_sopt7_adc$(_instance)pretrgsel" constant="false" optional="true"/>
      <aliasOption key="/SIM/sim_sopt7_adc$(_instance)trgsel"    constant="false" optional="true"/>
   </category>

   <xi:include href="_irqOption.xml"/>
      
   <template namespace="usbdm"><![CDATA[
   #ifndef USBDM_ADC_CLOCK_SOURCES_DEFINED
   #define USBDM_ADC_CLOCK_SOURCES_DEFINED
      \t/**
      \t * ADC input clock source.
      \t */
      \tenum AdcClockSource {
      \t   AdcClockSource_PccAdcClk  = ADC_CFG1_ADICLK(0), //!< Clock from PCC_ADCn multiplexor
      \t   AdcClockSource_Reserved1  = ADC_CFG1_ADICLK(1), //!< Reserved
      \t   AdcClockSource_Reserved2  = ADC_CFG1_ADICLK(2), //!< Reserved
      \t   AdcClockSource_Reserved3  = ADC_CFG1_ADICLK(3), //!< Reserved
      \t   AdcClockSource_Default    = AdcClockSource_PccAdcClk
      \t};
   #endif\n\n
   ]]></template>
   
   <template><![CDATA[
     \t/**
     \t *  Get input clock frequency for ADC
     \t *  
     \t *  @param adcClockSource Clock source chosen for ADC
     \t *
     \t *  @return Frequency in Hz
     \t */
     \tstatic unsigned getInputClockFrequency(AdcClockSource adcClockSource) {
     \t
     \t   switch (adcClockSource) {
     \t      case AdcClockSource_Default:
     \t         return PccInfo::getAdc$(_instance)Frequency();
     \t      default:
     \t         return 0;
     \t   }
     \t}
     
     \t/**
     \t *  Get input clock frequency for ADC
     \t *
     \t *  @return Frequency in Hz
     \t */
     \tstatic unsigned getInputClockFrequency() {
     \t   return getInputClockFrequency(static_cast<AdcClockSource>(adc->CFG1 & ADC_CFG1_ADICLK_MASK));
     \t}\n\n
   ]]></template>
   
   <template><![CDATA[
     \t//! Default resolution
     \tstatic constexpr uint32_t defaultAdcResolution = ADC_CFG1_MODE($(adc_cfg1_mode));

     \t//! Default value for ADCx_CFG1 register
     \tstatic constexpr uint32_t cfg1  = 
     \t    ADC_CFG1_ADICLK(0)|
     \t    ADC_CFG1_MODE($(adc_cfg1_mode))|
     \t    ADC_CFG1_ADIV($(adc_cfg1_adiv));
     
     \t//! Default value for ADCx_CFG2 register
     \t static constexpr uint32_t cfg2  = 
     \t    ADC_CFG2_SMPLTS($(adc_cfg2_smplts));

     
     \t//! Default value for ADCx_SC2 register
     \tstatic constexpr uint32_t sc2  =
     \t    ADC_SC2_ACFE($(adc_sc2_acfe))|
     \t    ADC_SC2_ACFGT($(adc_sc2_acfgt))|
     \t    ADC_SC2_ACREN($(adc_sc2_acren))|
     \t    ADC_SC2_REFSEL($(adc_sc2_refsel))|
     \t    ADC_SC2_DMAEN($(adc_sc2_dmaen))|
     \t    ADC_SC2_ADTRG($(adc_sc2_adtrg));
     
     \t//! Default value for ADCx_CV1 register
     \tstatic constexpr uint32_t cv1  = $(adc_cv1);
     
     \t//! Default value for ADCx_CV2 register
     \tstatic constexpr uint32_t cv2  = $(adc_cv2);\n\n
   ]]></template>
   
   <template key="/ADC/declarations" namespace="all"  ><![CDATA[
   \t/**
   \t * Class representing $(_name)
   \t */
   \ttypedef AdcBase_T<$(_class)Info> $(_class);\n
   ]]></template>
      
   <signals/>
   
   <xi:include href="_clockOption.xml"/>

   <!-- validate
      class="net.sourceforge.usbdm.deviceEditor.validators.AdcValidate">
   </validate -->

   <projectActionList id = "adc_files" >
      <copy source="Project_Headers/adc_S32.h"                    target="Project_Headers/adc.h"                    overwrite="true"  derived="true" />
      <copy source="Snippets/analogue-comparison-example.cpp" target="Snippets/analogue-comparison-example.cpp" overwrite="true"  derived="true" />
      <copy source="Snippets/analogue-example.cpp"            target="Snippets/analogue-example.cpp"            overwrite="true"  derived="true" />
      <copy source="Snippets/analogue-diff-example.cpp"       target="Snippets/analogue-diff-example.cpp"       overwrite="true"  derived="true" />
      <copy source="Snippets/analogue-interrupt-example.cpp"  target="Snippets/analogue-interrupt-example.cpp"  overwrite="true"  derived="true" />
      <copy source="Snippets/analogue-joystick-example.cpp"   target="Snippets/analogue-joystick-example.cpp"   overwrite="true"  derived="true" />
   </projectActionList>
   
</peripheralPage>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/spi0_16bit_mkl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- spi0_16bit_mkl.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Serial Peripheral Interface">

   <xi:include href="_default_instance.xml"/>

   <xi:include href="_mapPinsOption_on.xml"/>
   
   <intOption name="speed" 
      description="Speed of interface"
      toolTip="Speed of transmission"
      value="10000000" units="Hz"
      min="0" max="10000000" />

   <choiceOption name="spi_mode"  
      description="Mode"
      toolTip="Communication mode">
      <choice value="0" name="Mode 0: CPOL=0, CPHA=0" isDefault="true" />
      <choice value="1" name="Mode 1: CPOL=0, CPHA=1" />
      <choice value="2" name="Mode 2: CPOL=1, CPHA=0" />
      <choice value="3" name="Mode 3: CPOL=1, CPHA=1" />
   </choiceOption>

   <binaryOption name="spi_lsbfe" 
      description="Transmission order"
      toolTip="Transmission order">
      <choice value="0" name="MSB first" />
      <choice value="1" name="LSB first" />
   </binaryOption>
      
   <projectActionList id = "spi_files" >
      <copy source="Project_Headers/spi_16bit-MKL.h"    target="Project_Headers/spi.h"  overwrite="true"  derived="true" />
      <copy source="Sources/spi_16bit-MKL.cpp"          target="Sources/spi.cpp"        overwrite="true"  derived="true" />
   </projectActionList>
   
   <xi:include href="_irqOption.xml"/>
   
   <xi:include href="_clockOption.xml"/>
   
   <validate
      class="net.sourceforge.usbdm.deviceEditor.validators.SpiValidate">
   </validate>

   <template><![CDATA[
      \t//! Default communication mode: order, clock phase and clock polarity
      \tstatic constexpr uint8_t modeValue = 
      \t   SPI_C1_LSBFE($(spi_lsbfe))| // LSB or MSB first
      \t   SPI_C1_MODE($(spi_mode));  // Mode (CPOL+CPHA)
      
      \tstatic uint32_t getClockFrequency() {
      \t   return SystemBusClock;
      \t}

      \t//! Default speed (Hz)\n
      \tstatic constexpr uint32_t speed = 
      \t   $(speed);\n\n
   ]]></template>

   <signals/>
</peripheralPage>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/dma0_4ch.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- dma0_4ch.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="DMA Module">

   <xi:include href="_default_instance.xml"/>

   <intOption key="NumChannels" constant="true" derived="true"
      description="Number of DMA channels" 
      toolTip="The number of DMA channels available" 
      value="4" />

   <intOption key="NumVectors" constant="true" derived="true"
      description="Number of DMA interrupt vectors" 
      toolTip="Number of DMA interrupt vectors - \n
               Multiple channels may be mapped to the same vector" 
      value="4" />
      
   <template><![CDATA[
      \t/** 
      \t *  Enable clock to $(_class)
      \t */
      \tstatic void enableClock() {
      #ifdef PCC
      \t   // DMA is always clocked
      #else
      \t   $(clockEnable)
      #endif
      \t}

      \t/** 
      \t *  Disable clock to $(_class)
      \t */
      \tstatic void disableClock() {
      #ifdef PCC
      \t   // DMA is always clocked
      #else
      \t   $(clockDisable)
      #endif
      \t}\n\n
   ]]></template>
      
   <stringOption key="irq_pattern"        constant="true" value="^%b_?(\d+)(_DMA.*)?$;^%b_Error.*$" hidden="true" />
   <stringOption key="irq_classHandler"   constant="true" value="%c%i::irqHandler&lt;$1&gt;;%c%i::errorIrqHandler" hidden="true" />
   <xi:include href="_irqOptionSubstituted.xml"/>
 
   <validate
      class="net.sourceforge.usbdm.deviceEditor.validators.PeripheralValidator">
   </validate>

   <template key="/DMA/declarations" namespace="all"  ><![CDATA[
   \t/**
   \t * Class representing DMAMUX$(_instance)
   \t */
   \ttypedef $(_base_class)Mux_T<Dmamux$(_instance)Info, Dma$(_instance)Info::NumChannels> DmaMux$(_instance);
   \t/**
   \t * Class representing $(_name)
   \t */
   \ttypedef $(_base_class)Base_T<$(_class)Info> $(_class);\n
   ]]></template>
      
   <template><![CDATA[
      \t//! Number of DMA channels implemented
      \tstatic constexpr unsigned NumChannels = $(NumChannels);

      \t//! Number of DMA vectors implemented
      \tstatic constexpr unsigned NumVectors = $(NumVectors);\n\n
   ]]></template>
   
   <projectActionList id = "dma_files" >
      <copy source="Project_Headers/dma-MK.h"                   target="Project_Headers/dma.h"                      overwrite="true"  derived="true" />
      <copy source="Snippets/dma-memory-example.cpp"            target="Snippets/dma-memory-example.cpp"            overwrite="true"  derived="true" />
      <copy source="Snippets/dma-memory-template-example.cpp"   target="Snippets/dma-memory-template-example.cpp"   overwrite="true"  derived="true" />
      <copy source="Snippets/dma-uart-example-mk20.cpp"         target="Snippets/dma-uart-example-mk20.cpp"         overwrite="true"  derived="true" />
      <copy source="Snippets/dma-uart-example-mk22f.cpp"        target="Snippets/dma-uart-example-mk22f.cpp"        overwrite="true"  derived="true" />
      <copy source="Snippets/dma-uart-example-mk28f.cpp"        target="Snippets/dma-uart-example-mk28f.cpp"        overwrite="true"  derived="true" />
      <copy source="Snippets/dma-spi-example.cpp"               target="Snippets/dma-spi-example.cpp"               overwrite="true"  derived="true" />
      <copy source="Snippets/pit-adc-dma-example.cpp"           target="Snippets/pit-adc-dma-example.cpp"           overwrite="true"  derived="true" />
   </projectActionList>

</peripheralPage>
