=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/Menu.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root fileElement -->
<!ELEMENT root ((page|menu*),validate*,template) >
   <!ATTLIST root xmlns:xi CDATA #IMPLIED>

<!ELEMENT page ((intOption|choiceOption|binaryOption|stringOption|aliasOption|xi:include|menu)*) >
   <!ATTLIST page xmlns:xi CDATA #IMPLIED>
   <!ATTLIST page name         CDATA        #REQUIRED>
   <!ATTLIST page description  CDATA        #REQUIRED>
   
<!ELEMENT menu ((intOption|choiceOption|binaryOption|stringOption|aliasOption|xi:include|menu)*) >
   <!ATTLIST menu xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST menu name         CDATA        #REQUIRED>
   <!ATTLIST menu key          CDATA        #IMPLIED>
   <!ATTLIST menu description  CDATA        #REQUIRED>
   <!ATTLIST menu toolTip      CDATA        "">
   
<!ELEMENT intOption EMPTY >
   <!ATTLIST intOption constant     (false|true) "false">
   <!ATTLIST intOption name         CDATA        #REQUIRED>
   <!ATTLIST intOption key          CDATA        #IMPLIED>
   <!ATTLIST intOption description  CDATA        #REQUIRED>
   <!ATTLIST intOption toolTip      CDATA        "">
   <!ATTLIST intOption value        CDATA        "0">
   <!ATTLIST intOption units        (None|Hz|Seconds)    "None">
   <!ATTLIST intOption step         CDATA        "1">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST intOption min          CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST intOption max          CDATA        #IMPLIED>
   <!-- Offset to translate from displayed value to substitution value -->
   <!ATTLIST intOption offset       CDATA        "0">
  
<!ELEMENT aliasOption EMPTY >
   <!ATTLIST aliasOption name         CDATA        #REQUIRED>

<!ELEMENT stringOption EMPTY >
   <!ATTLIST stringOption constant     (false|true) "false">
   <!ATTLIST stringOption name         CDATA        #REQUIRED>
   <!ATTLIST stringOption key          CDATA        #IMPLIED>
   <!ATTLIST stringOption description  CDATA        #REQUIRED>
   <!ATTLIST stringOption toolTip      CDATA        "">
   <!ATTLIST stringOption value        CDATA        "0">
  
<!ELEMENT choiceOption (choice)+ >
   <!ATTLIST choiceOption constant     (false|true) "false">
   <!ATTLIST choiceOption name         CDATA        #REQUIRED>
   <!ATTLIST choiceOption key          CDATA        #IMPLIED>
   <!ATTLIST choiceOption description  CDATA        #REQUIRED>
   <!ATTLIST choiceOption toolTip      CDATA        "">
   <!ATTLIST choiceOption units        (None|Hz|Seconds)    "None">
  
<!ELEMENT choice EMPTY >
   <!ATTLIST choice value        CDATA        #REQUIRED>
   <!ATTLIST choice name         CDATA        #REQUIRED>
   <!ATTLIST choice isDefault    (false|true) "false">

<!ELEMENT binaryOption (choice, choice, (intOption|choiceOption|binaryOption|stringOption|aliasOption|xi:include|menu)*) >
   <!ATTLIST binaryOption constant     (false|true) "false">
   <!ATTLIST binaryOption name         CDATA        #REQUIRED>
   <!ATTLIST binaryOption key          CDATA        #IMPLIED>
   <!ATTLIST binaryOption description  CDATA        #REQUIRED>
   <!ATTLIST binaryOption toolTip      CDATA        "">

<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>

<!ELEMENT template (#PCDATA)>
   <!ELEMENT validate (param*) >
   <!ATTLIST validate class CDATA #REQUIRED>
   
<!ELEMENT param EMPTY >
   <!ATTLIST param type  (int|string) #REQUIRED>
   <!ATTLIST param value CDATA        #REQUIRED>

=== podonoghue/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/Spi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "Menu.dtd" >
<!-- ftm.xml -->

<root xmlns:xi="http://www.w3.org/2001/XInclude">
   <menu name="_instance" description="Flex timer">
      <choiceOption name="MODE" description="Mode"
         toolTip="Communication mode">
         <choice value="0" name="Mode 0: CPOL=0, CPHA=0" />
         <choice value="1" name="Mode 1: CPOL=0, CPHA=1" />
         <choice value="2" name="Mode 2: CPOL=1, CPHA=0" />
         <choice value="3" name="Mode 3: CPOL=1, CPHA=1" />
         <choice value="1" name="Default" />
      </choiceOption>

      <intOption name="SPEED" description="Speed"
         toolTip="Speed of transmission"
         value="100000" min="0" max="10000000" />

      <binaryOption name="LSBFE" description="Transmission order"
         toolTip="Transmission order">
         <choice value="0" name="MSB first" />
         <choice value="1" name="LSB first" />
      </binaryOption>

      <binaryOption name="IRQ_HANDLER" description="Handler for IRQ"
         toolTip="Polling or interrupts may be used to update the state machine">
         <choice value="0" name="Use polling" />
         <choice value="1" name="Use interrupts" />
      </binaryOption>

      <intOption name="IRQ_LEVEL" description="IRQ Level in NVIC [0-15]"
         toolTip="Sets the priority level used to configure the NVIC"
         value="0" min="0" max="15" />
   </menu>
   <template>
      #ifdef SPI_CTAR_LSBFE_SHIFT\n
      \t//! Default communication mode: order, clock phase and clock polarity\n
      \tstatic constexpr uint32_t modeValue = ($(LSBFE)&lt;&lt;SPI_CTAR_LSBFE_SHIFT)|($(MODE)&lt;&lt;SPI_CTAR_CPHA_SHIFT);\n\n
      #endif\n
      \t//! Default speed (Hz)\n
      \tstatic constexpr uint32_t speed = $(SPEED);\n\n
       \t//! Default IRQ level\n
       \tstatic constexpr uint32_t irqLevel =  $(IRQ_LEVEL);\n\n
   </template>
</root>
